# Toy Core Configuration (demo frontend)

balldomain = "balldomains/default.toml"
memdomain = "memdomains/default.toml"
frontend = "frontends/demo.toml"
rvv = "rvv/default.toml"
cpu = "cpu/default.toml"
