# Toy Core Configuration (demo frontend)

balldomain = "balldomains/default.toml"
memdomain = "memdomains/default.toml"
frontend = "frontends/demo.toml"
gpdomain = "gpdomains/default.toml"
cpu = "cpu/default.toml"
