[workloads]
search_path = "workloads/src"
tests = [
  "toy_mvin_mvout_test-linux",
  "toy_mvin_mvout_stride_test-linux",
  "toy_vecunit_matmul_16xn_ones-linux",
  "toy_vecunit_matmul_16xn_random1-linux",
  "toy_vecunit_matmul_16xn_random2-linux",
  "toy_vecunit_matmul_16xn_random3-linux",
  "toy_vecunit_matmul_16xn_zero_random-linux",
  "toy_vecunit_matmul_col_row_vector-linux",
  "toy_vecunit_matmul_identity_random-linux",
  "toy_vecunit_matmul_ones-linux",
  "toy_vecunit_matmul_random1-linux",
  "toy_vecunit_matmul_random2-linux",
  "toy_vecunit_matmul_zero_random-linux",
  "toy_relu_test-linux",
  "toy_transpose_i8_16x16_test-linux",
  "toy_transpose_i8_16x32_test-linux",
  "toy_transpose_i32_8x16_test-linux",
  "toy_transpose_bank_i8_n1_1024x16_test-linux",
  "toy_transpose_bank_i8_n2_1024x32_test-linux",
  "toy_transpose_bank_i32_n4_1024x16_test-linux",
  "toy_im2col_k1_test-linux",
  "toy_im2col_k3_test-linux",
  "toy_im2col_k3_partial_test-linux",
  "toy_im2col_k3_pad_test-linux",
  "toy_im2col_k5_test-linux",
  "toy_im2col_k7_test-linux",
  "toy_im2col_bank_k1_test-linux",
  "toy_im2col_bank_k3_test-linux",
  "toy_im2col_bank_k5_test-linux",
  "toy_im2col_bank_k7_test-linux",
  "toy_bdb_counter_test-linux",
  "toy_matrix_test-linux",
  "toy_gemmini_os_cisc_basic_test-linux",
  "toy_gemmini_os_cisc_atranspose_test-linux",
  "toy_gemmini_os_cisc_btranspose_test-linux",
  "toy_gemmini_os_cisc_shift_test-linux",
  "toy_gemmini_os_risc_atranspose_test-linux",
  "toy_gemmini_os_risc_btranspose_test-linux",
  "toy_gemmini_os_risc_abtranspose_test-linux",
  "toy_gemmini_os_risc_shift_test-linux",
  "toy_gemmini_ws_cisc_conv_test-linux",
  "toy_gemmini_ws_risc_basic_test-linux",
  "toy_mmio_minimal_test-linux",
  "toy_mxfp2int_test-linux",
  "toy_fp2int_fp32_to_int32_test-linux",
  "toy_fp2int_fp32_to_int8_test-linux",
  "toy_int2fp_int32_to_fp32_test-linux",
  "toy_int2fp_int8_to_fp32_test-linux",
  "toy_int2fp_int32_to_int8_test-linux",
  "toy_int2fp_int32_to_fp32_col2_test-linux",
  "toy_int2fp_int32_to_fp32_col4_test-linux",
  "toy_fp2int_bank_fp32_to_int32_test-linux",
  "toy_fp2int_bank_fp32_to_int8_test-linux",
  "toy_int2fp_bank_int32_to_fp32_test-linux",
  "toy_int2fp_bank_int8_to_fp32_test-linux",
  "toy_int2fp_bank_int32_to_int8_test-linux",
  "toy_int2fp_bank_int32_to_fp32_col2_test-linux",
  "toy_int2fp_bank_int32_to_fp32_col4_test-linux",
  "toy_optest_buckyball_matmul_16x64_64x16-linux",
  "toy_optest_buckyball_matmul_64x16_16x64-linux",
  "toy_optest_buckyball_matmul_1024x16_16x1024-linux",
  "toy_optest_tile_matmul_127x17_17x127-linux",
  "toy_optest_tile_matmul_1x84_84x10-linux",
  "toy_optest_linalg_conv2d_nhwc_hwcf-linux",
  "toy_optest_linalg_conv2d_nhwc_fhwc-linux",
  "toy_optest_linalg_conv2d_nchw_fchw-linux",
]
