[workloads]
search_path = "workloads/src"
tests = [
  "toy_mvin_mvout_test-rushB-bemu-run",
  "toy_mvin_mvout_stride_test-rushB-bemu-run",
  "toy_vecunit_matmul_16xn_ones-rushB-bemu-run",
  "toy_vecunit_matmul_16xn_random1-rushB-bemu-run",
  "toy_vecunit_matmul_16xn_random2-rushB-bemu-run",
  "toy_vecunit_matmul_16xn_random3-rushB-bemu-run",
  "toy_vecunit_matmul_16xn_zero_random-rushB-bemu-run",
  "toy_vecunit_matmul_col_row_vector-rushB-bemu-run",
  "toy_vecunit_matmul_identity_random-rushB-bemu-run",
  "toy_vecunit_matmul_ones-rushB-bemu-run",
  "toy_vecunit_matmul_random1-rushB-bemu-run",
  "toy_vecunit_matmul_random2-rushB-bemu-run",
  "toy_vecunit_matmul_zero_random-rushB-bemu-run",
  "toy_relu_test-rushB-bemu-run",
  "toy_transpose_i8_16x16_test-rushB-bemu-run",
  "toy_transpose_i8_16x32_test-rushB-bemu-run",
  "toy_transpose_i32_8x16_test-rushB-bemu-run",
  "toy_transpose_bank_i8_n1_1024x16_test-rushB-bemu-run",
  "toy_transpose_bank_i8_n2_1024x32_test-rushB-bemu-run",
  "toy_transpose_bank_i32_n4_1024x16_test-rushB-bemu-run",
  "toy_im2col_k1_test-rushB-bemu-run",
  "toy_im2col_k3_test-rushB-bemu-run",
  "toy_im2col_k3_partial_test-rushB-bemu-run",
  "toy_im2col_k3_pad_test-rushB-bemu-run",
  "toy_im2col_k5_test-rushB-bemu-run",
  "toy_im2col_k7_test-rushB-bemu-run",
  "toy_im2col_bank_k1_test-rushB-bemu-run",
  "toy_im2col_bank_k3_test-rushB-bemu-run",
  "toy_im2col_bank_k5_test-rushB-bemu-run",
  "toy_im2col_bank_k7_test-rushB-bemu-run",
  "toy_bdb_counter_test-rushB-bemu-run",
  "toy_matrix_os_4x4_test-rushB-bemu-run",
  "toy_matrix_ws_4x4_test-rushB-bemu-run",
  "toy_matrix_os_16x16_test-rushB-bemu-run",
  "toy_matrix_ws_16x16_test-rushB-bemu-run",
  "toy_matrix_os_32x16_test-rushB-bemu-run",
  "toy_matrix_ws_32x16_test-rushB-bemu-run",
  "toy_matrix_os_16x16_ones-rushB-bemu-run",
  "toy_matrix_os_32x32_ones-rushB-bemu-run",
  "toy_matrix_os_tail_5x7x3_test-rushB-bemu-run",
  "toy_matrix_mode_switch_test-rushB-bemu-run",
  "toy_matrix_bank_os_1024x16x16_test-rushB-bemu-run",
  "toy_matrix_bank_ws_1024x16x16_test-rushB-bemu-run",
  "toy_gemmini_os_risc_atranspose_test-rushB-bemu-run",
  "toy_gemmini_os_risc_btranspose_test-rushB-bemu-run",
  "toy_gemmini_os_risc_abtranspose_test-rushB-bemu-run",
  "toy_gemmini_os_risc_shift_test-rushB-bemu-run",
  "toy_gemmini_ws_risc_basic_test-rushB-bemu-run",
  "toy_fp2int_fp32_to_int32_test-rushB-bemu-run",
  "toy_fp2int_fp32_to_int8_test-rushB-bemu-run",
  "toy_int2fp_int32_to_fp32_test-rushB-bemu-run",
  "toy_int2fp_int8_to_fp32_test-rushB-bemu-run",
  "toy_int2fp_int32_to_int8_test-rushB-bemu-run",
  "toy_int2fp_int32_to_fp32_col2_test-rushB-bemu-run",
  "toy_int2fp_int32_to_fp32_col4_test-rushB-bemu-run",
  "toy_fp2int_bank_fp32_to_int32_test-rushB-bemu-run",
  "toy_fp2int_bank_fp32_to_int8_test-rushB-bemu-run",
  "toy_int2fp_bank_int32_to_fp32_test-rushB-bemu-run",
  "toy_int2fp_bank_int8_to_fp32_test-rushB-bemu-run",
  "toy_int2fp_bank_int32_to_int8_test-rushB-bemu-run",
  "toy_int2fp_bank_int32_to_fp32_col2_test-rushB-bemu-run",
  "toy_int2fp_bank_int32_to_fp32_col4_test-rushB-bemu-run",
  "toy_optest_buckyball_matmul_16x64_64x16-rushB-bemu-run",
  "toy_optest_buckyball_matmul_64x16_16x64-rushB-bemu-run",
  "toy_optest_buckyball_matmul_1024x16_16x1024-rushB-bemu-run",
  "toy_optest_tile_matmul_127x17_17x127-rushB-bemu-run",
  "toy_optest_tile_matmul_1x84_84x10-rushB-bemu-run",
  "toy_optest_linalg_conv2d_nhwc_hwcf-rushB-bemu-run",
  "toy_optest_linalg_conv2d_nhwc_fhwc-rushB-bemu-run",
  "toy_optest_linalg_conv2d_nchw_fchw-rushB-bemu-run",
]
