[workloads]
tests = [
  "toy-toy-ctest-rvv_vsetvli_e32_m1_vl_test-baremetal",
  "toy-toy-ctest-mvin_mvout_test-baremetal",
  "toy-toy-ctest-mvin_mvout_stride_test-baremetal",
  "toy-toy-ctest-bdb_counter_start_stop_test-baremetal",
  "toy-toy-ctest-bdb_counter_read_active_test-baremetal",
  "toy-toy-ctest-bdb_counter_nested_pair_test-baremetal",
  "toy-toy-ctest-bdb_counter_multi_id_test-baremetal",
  "toy-toy-mlirtest-ball_bdb_counter_start_read_stop-baremetal",
  "toy-toy-ctest-gemmini_os_cisc_basic_test-baremetal",
  "toy-toy-ctest-gemmini_os_cisc_atranspose_test-baremetal",
  "toy-toy-ctest-gemmini_os_cisc_btranspose_test-baremetal",
  "toy-toy-ctest-gemmini_os_cisc_shift_test-baremetal",
  "toy-toy-ctest-gemmini_os_risc_atranspose_test-baremetal",
  "toy-toy-ctest-gemmini_os_risc_btranspose_test-baremetal",
  "toy-toy-ctest-gemmini_os_risc_abtranspose_test-baremetal",
  "toy-toy-ctest-gemmini_os_risc_shift_test-baremetal",
  "toy-toy-ctest-gemmini_ws_cisc_conv_test-baremetal",
  "toy-toy-ctest-gemmini_ws_risc_basic_test-baremetal",
  "toy-toy-ctest-mmio_minimal_test-baremetal",
  "toy-toy-ctest-mxfp4_e8m0_two_block_test-baremetal",
  "toy-toy-ctest-relu_i32_16x16_test-baremetal",
  "toy-toy-mlirtest-ball_relu_i32_16row-baremetal",
  "toy-toy-mlirtest-bank_relu_i32_mixed_sign-baremetal",
  "toy-toy-mlirtest-bank_mxfp4_unit_scale_bank-baremetal",
  "toy-toy-mlirtest-ball_mxfp4_unit_scale_2blocks-baremetal",
  "toy-toy-mlirtest-bank_gemmini_compute_preloaded_bank_tiles-baremetal",
  "toy-toy-mlirtest-bank_gemmini_compute_accumulated_bank_tiles-baremetal",
]
