[workloads]
search_path = "workloads/src"
tests = [
  "mvin_mvout_test-linux",
  "mvin_mvout_stride_test-linux",
  "vecunit_matmul_16xn_ones-linux",
  "vecunit_matmul_16xn_random1-linux",
  "vecunit_matmul_16xn_random2-linux",
  "vecunit_matmul_16xn_random3-linux",
  "vecunit_matmul_16xn_zero_random-linux",
  "vecunit_matmul_col_row_vector-linux",
  "vecunit_matmul_identity_random-linux",
  "vecunit_matmul_ones-linux",
  "vecunit_matmul_random1-linux",
  "vecunit_matmul_random2-linux",
  "vecunit_matmul_zero_random-linux",
  "relu_test-linux",
  "transpose_test-linux",
  "transpose_16xn_test-linux",
  "im2col_test-linux",
  "fp2int_test-linux",
  "int2fp_test-linux",
  "bdb_counter_test-linux",
  "bfp_test-linux",
  "gemmini_os_cisc_basic_test-linux",
  "gemmini_os_cisc_atranspose_test-linux",
  "gemmini_os_cisc_btranspose_test-linux",
  "gemmini_os_cisc_shift_test-linux",
  "gemmini_os_risc_atranspose_test-linux",
  "gemmini_os_risc_btranspose_test-linux",
  "gemmini_os_risc_abtranspose_test-linux",
  "gemmini_os_risc_shift_test-linux",
  "gemmini_ws_cisc_conv_test-linux",
  "gemmini_ws_risc_basic_test-linux",
  "mmio_minimal_test-linux",
  "mxfp2int_test-linux",
  "optest_buckyball_matmul_16x64_64x16-linux",
  "optest_buckyball_matmul_64x16_16x64-linux",
  "optest_buckyball_matmul_1024x16_16x1024-linux",
  "optest_tile_matmul_127x17_17x127-linux",
  "optest_tile_matmul_1x84_84x10-linux",
  "optest_linalg_conv2d_nhwc_hwcf-linux",
  "optest_linalg_conv2d_nhwc_fhwc-linux",
  "optest_linalg_conv2d_nchw_fchw-linux",
]
