/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'FinalEvent': EventHandler<{}, never>
    'InstallChipyard': EventHandler<{}, { topic: 'install-chipyard-finished'; data: {} }>
    'build-setupAPI': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'start'; data: {} }>
    'InstallXXTool': EventHandler<{}, never>
    'InstallAnaconda': EventHandler<{}, never>
    'option-installAPI': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'option-install'; data: {} }>
  }
}