/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'build workload': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'workload.build'; data: never }>
    'verilator error': EventHandler<never, never>
    'verilator complete': EventHandler<never, never>
    'Verilator Complete Workflow': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'verilator.run'; data: never }>
    'make sim': EventHandler<never, { topic: 'verilator.complete'; data: never } | { topic: 'verilator.error'; data: never }>
    'Verilator Sim': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'verilator.sim'; data: never }>
    'make build': EventHandler<never, { topic: 'verilator.sim'; data: never } | { topic: 'verilator.complete'; data: never } | { topic: 'verilator.error'; data: never }>
    'Verilator Build': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'verilator.build'; data: never }>
    'make verilog': EventHandler<never, { topic: 'verilator.build'; data: never } | { topic: 'verilator.complete'; data: never } | { topic: 'verilator.error'; data: never }>
    'Verilator Verilog': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'verilator.verilog'; data: never }>
    'make clean': EventHandler<never, { topic: 'verilator.verilog'; data: never } | { topic: 'verilator.complete'; data: never } | { topic: 'verilator.error'; data: never }>
    'Verilator Clean': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'verilator.clean'; data: never }>
    'running sardine': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'sardine.run'; data: never }>
    'Marshal Launch': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'marshal.launch'; data: never }>
    'Marshal Build': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'marshal.build'; data: never }>
    'build functional simulator': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'funcsim.build'; data: never }>
    'Firesim Runworkload': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'firesim.runworkload'; data: never }>
    'Firesim Infrasetup': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'firesim.infrasetup'; data: never }>
    'Firesim Buildbitstream': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'firesim.buildbitstream'; data: never }>
    'Build Compiler': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'compiler.build'; data: never }>
    'agent': ApiRouteHandler<{ message: string; model?: string }, ApiResponse<200, { traceId?: string; status?: string }>, { topic: 'agent.prompt'; data: { message?: string; model?: string; traceId?: string } }>
  }
}