`ifndef CHI_PROFILE_SVH
`define CHI_PROFILE_SVH
`ifndef CHI_DATA_BITS
`define CHI_DATA_BITS 256
`endif
`define CHI_BE_BITS (`CHI_DATA_BITS / 8)
`define CHI_TAG_BITS (`CHI_DATA_BITS / 32)
`define CHI_TAG_UPDATE_BITS (`CHI_DATA_BITS / 128)
`define CHI_DAT_BITS (91 + `CHI_DATA_BITS + `CHI_BE_BITS + `CHI_TAG_BITS + `CHI_TAG_UPDATE_BITS)
`define CHI_BEATS (512 / `CHI_DATA_BITS)
`define CHI_DATA_ID_STEP (`CHI_DATA_BITS / 128)
`endif
