// Format Version: 2
// Exact reviewed objects; grouped scopes and proofs, with equivalent adjacent bit/transition ranges.

CHECKSUM: "1565409055 1106117561"
INSTANCE: retry_tb.dut
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Unsupported CHI retry request opcode"
Block 2 "1744103448" "if (1)"
Block 3 "675298159" "$error(\"Assertion failed: Unsupported CHI retry request opcode\n    at RequestRetry.scala:64 assert(coherent || noSnoop, \\"Unsupported CHI retry request opcode\\")\n\");"
Block 5 "1744103448" "if (1)"
Block 6 "3310318889" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Unsupported CHI retry request attributes"
Block 10 "3534321110" "if (1)"
Block 11 "3076932440" "$error(\"Assertion failed: Unsupported CHI retry request attributes\n    at RequestRetry.scala:65 assert(\n\");"
Block 13 "3534321110" "if (1)"
Block 14 "882429221" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Invalid retry completion-ack profile"
Block 18 "3921772647" "if (1)"
Block 19 "3527252594" "$error(\"Assertion failed: Invalid retry completion-ack profile\n    at RequestRetry.scala:71 assert(r.expCompAck === coherentRead.asUInt, \\"Invalid retry completion-ack profile\\")\n\");"
Block 21 "3921772647" "if (1)"
Block 22 "2211796926" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Invalid retry coherent request attributes"
Block 26 "568216364" "if (1)"
Block 27 "439395600" "$error(\"Assertion failed: Invalid retry coherent request attributes\n    at RequestRetry.scala:73 assert(r.returnNid === 0.U && r.returnTxnId === 0.U && r.memAttr === 12.U && r.snpAttr === 1.U,\n\");"
Block 29 "568216364" "if (1)"
Block 30 "1967310581" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Invalid retry non-snoop request attributes"
Block 34 "2827715915" "if (1)"
Block 35 "4275880477" "$error(\"Assertion failed: Invalid retry non-snoop request attributes\n    at RequestRetry.scala:76 assert(!r.memAttr(1) && r.snpAttr === 0.U, \\"Invalid retry non-snoop request attributes\\")\n\");"
Block 37 "2827715915" "if (1)"
Block 38 "246045839" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Invalid retry requester"
Block 42 "1709660459" "if (1)"
Block 43 "4204837901" "$error(\"Assertion failed: Invalid retry requester\n    at RequestRetry.scala:78 assert(io.reqIn.bits.srcId === nodeId.U, \\"Invalid retry requester\\")\n\");"
Block 45 "1709660459" "if (1)"
Block 46 "2514228879" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: CHI retry requester reused a live TxnID"
Block 50 "1112493139" "if (1)"
Block 51 "2040280706" "$error(\"Assertion failed: CHI retry requester reused a live TxnID\n    at RequestRetry.scala:79 assert(!duplicate, \\"CHI retry requester reused a live TxnID\\")\n\");"
Block 53 "1112493139" "if (1)"
Block 54 "1089463653" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Initial CHI request must allow retry without a protocol credit"
Block 58 "130518244" "if (1)"
Block 59 "4023718724" "$error(\"Assertion failed: Initial CHI request must allow retry without a protocol credit\n    at RequestRetry.scala:80 assert(\n\");"
Block 61 "130518244" "if (1)"
Block 62 "422011914" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Response to wrong retry requester"
Block 66 "297091616" "if (1)"
Block 67 "3803880083" "$error(\"Assertion failed: Response to wrong retry requester\n    at RequestRetry.scala:131 assert(r.tgtId === nodeId.U, \\"Response to wrong retry requester\\")\n\");"
Block 69 "297091616" "if (1)"
Block 70 "3411174966" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Unexpected or repeated RetryAck"
Block 74 "2784317146" "if (1)"
Block 75 "3648346299" "$error(\"Assertion failed: Unexpected or repeated RetryAck\n    at RequestRetry.scala:135 assert(matches.asUInt.orR && state(i) === firstAttempt && r.respErr === 0.U, \\"Unexpected or repeated RetryAck\\")\n\");"
Block 77 "2784317146" "if (1)"
Block 78 "74728005" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Excess or errored protocol credit"
Block 82 "2447225933" "if (1)"
Block 83 "3962228737" "$error(\"Assertion failed: Excess or errored protocol credit\n    at RequestRetry.scala:142 assert(space.asUInt.orR && r.respErr === 0.U, \\"Excess or errored protocol credit\\")\n\");"
Block 85 "2447225933" "if (1)"
Block 86 "891196801" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Response accepted before request reissue"
Block 90 "3397368675" "if (1)"
Block 91 "2039620193" "$error(\"Assertion failed: Response accepted before request reissue\n    at RequestRetry.scala:124 assert(state(i) =/= retryWait, \\"Response accepted before request reissue\\")\n\");"
Block 93 "3397368675" "if (1)"
Block 94 "1797854015" "$fatal;"
Block 98 "397495833" "if (1)"
Block 99 "587374098" "$error(\"Assertion failed: Response accepted before request reissue\n    at RequestRetry.scala:124 assert(state(i) =/= retryWait, \\"Response accepted before request reissue\\")\n\");"
Block 101 "397495833" "if (1)"
Block 102 "834252620" "$fatal;"

CHECKSUM: "1565409055 2680414210"
INSTANCE: retry_tb.dut
ANNOTATION: "RequestRetry asserted legal request contract: NodeID1, 64-byte aligned access, supported opcodes below64, normal memory (Device=0), PAS/Order/exclusive/tag/multi-request/stash=0, LPID lower5 only. All higher address and arbitrary TxnID/routing bits stay measured."
Toggle io_reqOut_bits_srcId [6:0] "net io_reqOut_bits_srcId[6:0]"
Toggle io_reqOut_bits_stashNidValidEndian "net io_reqOut_bits_stashNidValidEndian"
Toggle io_reqOut_bits_opcode [6] "net io_reqOut_bits_opcode[6:0]"
Toggle io_reqOut_bits_multiReq "net io_reqOut_bits_multiReq"
Toggle io_reqOut_bits_size [5:0] "net io_reqOut_bits_size[5:0]"
Toggle io_reqOut_bits_addr [5:0] "net io_reqOut_bits_addr[43:0]"
Toggle io_reqOut_bits_pas [2:0] "net io_reqOut_bits_pas[2:0]"
Toggle io_reqOut_bits_order [1:0] "net io_reqOut_bits_order[1:0]"
Toggle io_reqOut_bits_memAttr [1] "net io_reqOut_bits_memAttr[3:0]"
Toggle io_reqOut_bits_lpid [7:5] "net io_reqOut_bits_lpid[7:0]"
Toggle io_reqOut_bits_exclSnoopMe "net io_reqOut_bits_exclSnoopMe"
Toggle io_reqOut_bits_tagOp [1:0] "net io_reqOut_bits_tagOp[1:0]"
Toggle _arb_io_out_bits_srcId [6:0] "net _arb_io_out_bits_srcId[6:0]"
Toggle _arb_io_out_bits_stashNidValidEndian "net _arb_io_out_bits_stashNidValidEndian"
Toggle _arb_io_out_bits_opcode [6] "net _arb_io_out_bits_opcode[6:0]"
Toggle _arb_io_out_bits_multiReq "net _arb_io_out_bits_multiReq"
Toggle _arb_io_out_bits_size [5:0] "net _arb_io_out_bits_size[5:0]"
Toggle _arb_io_out_bits_addr [5:0] "net _arb_io_out_bits_addr[43:0]"
Toggle _arb_io_out_bits_pas [2:0] "net _arb_io_out_bits_pas[2:0]"
Toggle _arb_io_out_bits_order [1:0] "net _arb_io_out_bits_order[1:0]"
Toggle _arb_io_out_bits_memAttr [1] "net _arb_io_out_bits_memAttr[3:0]"
Toggle _arb_io_out_bits_lpid [7:5] "net _arb_io_out_bits_lpid[7:0]"
Toggle _arb_io_out_bits_exclSnoopMe "net _arb_io_out_bits_exclSnoopMe"
Toggle _arb_io_out_bits_tagOp [1:0] "net _arb_io_out_bits_tagOp[1:0]"
Toggle requests_0_srcId [6:0] "reg requests_0_srcId[6:0]"
Toggle requests_0_stashNidValidEndian "reg requests_0_stashNidValidEndian"
Toggle requests_0_opcode [6] "reg requests_0_opcode[6:0]"
Toggle requests_0_multiReq "reg requests_0_multiReq"
Toggle requests_0_size [5:0] "reg requests_0_size[5:0]"
Toggle requests_0_addr [5:0] "reg requests_0_addr[43:0]"
Toggle requests_0_pas [2:0] "reg requests_0_pas[2:0]"
Toggle requests_0_order [1:0] "reg requests_0_order[1:0]"
Toggle requests_0_memAttr [1] "reg requests_0_memAttr[3:0]"
Toggle requests_0_lpid [7:5] "reg requests_0_lpid[7:0]"
Toggle requests_0_exclSnoopMe "reg requests_0_exclSnoopMe"
Toggle requests_0_tagOp [1:0] "reg requests_0_tagOp[1:0]"
Toggle requests_1_srcId [6:0] "reg requests_1_srcId[6:0]"
Toggle requests_1_stashNidValidEndian "reg requests_1_stashNidValidEndian"
Toggle requests_1_opcode [6] "reg requests_1_opcode[6:0]"
Toggle requests_1_multiReq "reg requests_1_multiReq"
Toggle requests_1_size [5:0] "reg requests_1_size[5:0]"
Toggle requests_1_addr [5:0] "reg requests_1_addr[43:0]"
Toggle requests_1_pas [2:0] "reg requests_1_pas[2:0]"
Toggle requests_1_order [1:0] "reg requests_1_order[1:0]"
Toggle requests_1_memAttr [1] "reg requests_1_memAttr[3:0]"
Toggle requests_1_lpid [7:5] "reg requests_1_lpid[7:0]"
Toggle requests_1_exclSnoopMe "reg requests_1_exclSnoopMe"
Toggle requests_1_tagOp [1:0] "reg requests_1_tagOp[1:0]"
Toggle requests_2_srcId [6:0] "reg requests_2_srcId[6:0]"
Toggle requests_2_stashNidValidEndian "reg requests_2_stashNidValidEndian"
Toggle requests_2_opcode [6] "reg requests_2_opcode[6:0]"
Toggle requests_2_multiReq "reg requests_2_multiReq"
Toggle requests_2_size [5:0] "reg requests_2_size[5:0]"
Toggle requests_2_addr [5:0] "reg requests_2_addr[43:0]"
Toggle requests_2_pas [2:0] "reg requests_2_pas[2:0]"
Toggle requests_2_order [1:0] "reg requests_2_order[1:0]"
Toggle requests_2_memAttr [1] "reg requests_2_memAttr[3:0]"
Toggle requests_2_lpid [7:5] "reg requests_2_lpid[7:0]"
Toggle requests_2_exclSnoopMe "reg requests_2_exclSnoopMe"
Toggle requests_2_tagOp [1:0] "reg requests_2_tagOp[1:0]"
Toggle requests_3_srcId [6:0] "reg requests_3_srcId[6:0]"
Toggle requests_3_stashNidValidEndian "reg requests_3_stashNidValidEndian"
Toggle requests_3_opcode [6] "reg requests_3_opcode[6:0]"
Toggle requests_3_multiReq "reg requests_3_multiReq"
Toggle requests_3_size [5:0] "reg requests_3_size[5:0]"
Toggle requests_3_addr [5:0] "reg requests_3_addr[43:0]"
Toggle requests_3_pas [2:0] "reg requests_3_pas[2:0]"
Toggle requests_3_order [1:0] "reg requests_3_order[1:0]"
Toggle requests_3_memAttr [1] "reg requests_3_memAttr[3:0]"
Toggle requests_3_lpid [7:5] "reg requests_3_lpid[7:0]"
Toggle requests_3_exclSnoopMe "reg requests_3_exclSnoopMe"
Toggle requests_3_tagOp [1:0] "reg requests_3_tagOp[1:0]"

CHECKSUM: "917436931 2269459522"
INSTANCE: retry_tb.dut.arb
ANNOTATION: "RequestRetry asserted legal request contract: NodeID1, 64-byte aligned access, supported opcodes below64, normal memory (Device=0), PAS/Order/exclusive/tag/multi-request/stash=0, LPID lower5 only. All higher address and arbitrary TxnID/routing bits stay measured."
Toggle io_in_1_bits_srcId [6:0] "net io_in_1_bits_srcId[6:0]"
Toggle io_in_1_bits_stashNidValidEndian "net io_in_1_bits_stashNidValidEndian"
Toggle io_in_1_bits_opcode [6] "net io_in_1_bits_opcode[6:0]"
Toggle io_in_1_bits_multiReq "net io_in_1_bits_multiReq"
Toggle io_in_1_bits_size [5:0] "net io_in_1_bits_size[5:0]"
Toggle io_in_1_bits_addr [5:0] "net io_in_1_bits_addr[43:0]"
Toggle io_in_1_bits_pas [2:0] "net io_in_1_bits_pas[2:0]"
Toggle io_in_1_bits_order [1:0] "net io_in_1_bits_order[1:0]"
Toggle io_in_1_bits_memAttr [1] "net io_in_1_bits_memAttr[3:0]"
Toggle io_in_1_bits_lpid [7:5] "net io_in_1_bits_lpid[7:0]"
Toggle io_in_1_bits_exclSnoopMe "net io_in_1_bits_exclSnoopMe"
Toggle io_in_1_bits_tagOp [1:0] "net io_in_1_bits_tagOp[1:0]"
Toggle io_in_2_bits_srcId [6:0] "net io_in_2_bits_srcId[6:0]"
Toggle io_in_2_bits_stashNidValidEndian "net io_in_2_bits_stashNidValidEndian"
Toggle io_in_2_bits_opcode [6] "net io_in_2_bits_opcode[6:0]"
Toggle io_in_2_bits_multiReq "net io_in_2_bits_multiReq"
Toggle io_in_2_bits_size [5:0] "net io_in_2_bits_size[5:0]"
Toggle io_in_2_bits_addr [5:0] "net io_in_2_bits_addr[43:0]"
Toggle io_in_2_bits_pas [2:0] "net io_in_2_bits_pas[2:0]"
Toggle io_in_2_bits_order [1:0] "net io_in_2_bits_order[1:0]"
Toggle io_in_2_bits_memAttr [1] "net io_in_2_bits_memAttr[3:0]"
Toggle io_in_2_bits_lpid [7:5] "net io_in_2_bits_lpid[7:0]"
Toggle io_in_2_bits_exclSnoopMe "net io_in_2_bits_exclSnoopMe"
Toggle io_in_2_bits_tagOp [1:0] "net io_in_2_bits_tagOp[1:0]"
Toggle io_in_3_bits_srcId [6:0] "net io_in_3_bits_srcId[6:0]"
Toggle io_in_3_bits_stashNidValidEndian "net io_in_3_bits_stashNidValidEndian"
Toggle io_in_3_bits_opcode [6] "net io_in_3_bits_opcode[6:0]"
Toggle io_in_3_bits_multiReq "net io_in_3_bits_multiReq"
Toggle io_in_3_bits_size [5:0] "net io_in_3_bits_size[5:0]"
Toggle io_in_3_bits_addr [5:0] "net io_in_3_bits_addr[43:0]"
Toggle io_in_3_bits_pas [2:0] "net io_in_3_bits_pas[2:0]"
Toggle io_in_3_bits_order [1:0] "net io_in_3_bits_order[1:0]"
Toggle io_in_3_bits_memAttr [1] "net io_in_3_bits_memAttr[3:0]"
Toggle io_in_3_bits_lpid [7:5] "net io_in_3_bits_lpid[7:0]"
Toggle io_in_3_bits_exclSnoopMe "net io_in_3_bits_exclSnoopMe"
Toggle io_in_3_bits_tagOp [1:0] "net io_in_3_bits_tagOp[1:0]"
Toggle io_in_4_bits_srcId [6:0] "net io_in_4_bits_srcId[6:0]"
Toggle io_in_4_bits_stashNidValidEndian "net io_in_4_bits_stashNidValidEndian"
Toggle io_in_4_bits_opcode [6] "net io_in_4_bits_opcode[6:0]"
Toggle io_in_4_bits_multiReq "net io_in_4_bits_multiReq"
Toggle io_in_4_bits_size [5:0] "net io_in_4_bits_size[5:0]"
Toggle io_in_4_bits_addr [5:0] "net io_in_4_bits_addr[43:0]"
Toggle io_in_4_bits_pas [2:0] "net io_in_4_bits_pas[2:0]"
Toggle io_in_4_bits_order [1:0] "net io_in_4_bits_order[1:0]"
Toggle io_in_4_bits_memAttr [1] "net io_in_4_bits_memAttr[3:0]"
Toggle io_in_4_bits_lpid [7:5] "net io_in_4_bits_lpid[7:0]"
Toggle io_in_4_bits_exclSnoopMe "net io_in_4_bits_exclSnoopMe"
Toggle io_in_4_bits_tagOp [1:0] "net io_in_4_bits_tagOp[1:0]"
Toggle io_out_bits_srcId [6:0] "net io_out_bits_srcId[6:0]"
Toggle io_out_bits_stashNidValidEndian "net io_out_bits_stashNidValidEndian"
Toggle io_out_bits_opcode [6] "net io_out_bits_opcode[6:0]"
Toggle io_out_bits_multiReq "net io_out_bits_multiReq"
Toggle io_out_bits_size [5:0] "net io_out_bits_size[5:0]"
Toggle io_out_bits_addr [5:0] "net io_out_bits_addr[43:0]"
Toggle io_out_bits_pas [2:0] "net io_out_bits_pas[2:0]"
Toggle io_out_bits_order [1:0] "net io_out_bits_order[1:0]"
Toggle io_out_bits_memAttr [1] "net io_out_bits_memAttr[3:0]"
Toggle io_out_bits_lpid [7:5] "net io_out_bits_lpid[7:0]"
Toggle io_out_bits_exclSnoopMe "net io_out_bits_exclSnoopMe"
Toggle io_out_bits_tagOp [1:0] "net io_out_bits_tagOp[1:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured srcId of replay port1. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_2 [1][6:0] "net [7:0][6:0]_GEN_2"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured srcId of replay port2. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_2 [2][6:0] "net [7:0][6:0]_GEN_2"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured srcId of replay port3. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_2 [3][6:0] "net [7:0][6:0]_GEN_2"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured srcId of replay port4. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_2 [4][6:0] "net [7:0][6:0]_GEN_2"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured stashNidValidEndian of replay port1. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_5 [1] "net _GEN_5[7:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured stashNidValidEndian of replay port2. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_5 [2] "net _GEN_5[7:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured stashNidValidEndian of replay port3. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_5 [3] "net _GEN_5[7:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured stashNidValidEndian of replay port4. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_5 [4] "net _GEN_5[7:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured opcode of replay port1. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_7 [1][6] "net [7:0][6:0]_GEN_7"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured opcode of replay port2. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_7 [2][6] "net [7:0][6:0]_GEN_7"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured opcode of replay port3. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_7 [3][6] "net [7:0][6:0]_GEN_7"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured opcode of replay port4. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_7 [4][6] "net [7:0][6:0]_GEN_7"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured multiReq of replay port1. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_8 [1] "net _GEN_8[7:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured multiReq of replay port2. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_8 [2] "net _GEN_8[7:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured multiReq of replay port3. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_8 [3] "net _GEN_8[7:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured multiReq of replay port4. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_8 [4] "net _GEN_8[7:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured size of replay port1. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_9 [1][5:0] "net [7:0][5:0]_GEN_9"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured size of replay port2. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_9 [2][5:0] "net [7:0][5:0]_GEN_9"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured size of replay port3. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_9 [3][5:0] "net [7:0][5:0]_GEN_9"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured size of replay port4. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_9 [4][5:0] "net [7:0][5:0]_GEN_9"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured addr of replay port1. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_10 [1][5:0] "net [7:0][43:0]_GEN_10"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured addr of replay port2. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_10 [2][5:0] "net [7:0][43:0]_GEN_10"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured addr of replay port3. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_10 [3][5:0] "net [7:0][43:0]_GEN_10"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured addr of replay port4. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_10 [4][5:0] "net [7:0][43:0]_GEN_10"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured pas of replay port1. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_11 [1][2:0] "net [7:0][2:0]_GEN_11"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured pas of replay port2. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_11 [2][2:0] "net [7:0][2:0]_GEN_11"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured pas of replay port3. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_11 [3][2:0] "net [7:0][2:0]_GEN_11"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured pas of replay port4. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_11 [4][2:0] "net [7:0][2:0]_GEN_11"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is literal 1'h0. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_13 [4:1] "net _GEN_13[7:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured order of replay port1. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_14 [1][1:0] "net [7:0][1:0]_GEN_14"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured order of replay port2. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_14 [2][1:0] "net [7:0][1:0]_GEN_14"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured order of replay port3. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_14 [3][1:0] "net [7:0][1:0]_GEN_14"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured order of replay port4. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_14 [4][1:0] "net [7:0][1:0]_GEN_14"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured memAttr of replay port1. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_16 [1][1] "net [7:0][3:0]_GEN_16"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured memAttr of replay port2. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_16 [2][1] "net [7:0][3:0]_GEN_16"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured memAttr of replay port3. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_16 [3][1] "net [7:0][3:0]_GEN_16"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured memAttr of replay port4. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_16 [4][1] "net [7:0][3:0]_GEN_16"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured lpid of replay port1. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_18 [1][7:5] "net [7:0][7:0]_GEN_18"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured lpid of replay port2. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_18 [2][7:5] "net [7:0][7:0]_GEN_18"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured lpid of replay port3. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_18 [3][7:5] "net [7:0][7:0]_GEN_18"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured lpid of replay port4. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_18 [4][7:5] "net [7:0][7:0]_GEN_18"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured exclSnoopMe of replay port1. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_19 [1] "net _GEN_19[7:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured exclSnoopMe of replay port2. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_19 [2] "net _GEN_19[7:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured exclSnoopMe of replay port3. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_19 [3] "net _GEN_19[7:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured exclSnoopMe of replay port4. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_19 [4] "net _GEN_19[7:0]"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured tagOp of replay port1. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_21 [1][1:0] "net [7:0][1:0]_GEN_21"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured tagOp of replay port2. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_21 [2][1:0] "net [7:0][1:0]_GEN_21"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured tagOp of replay port3. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_21 [3][1:0] "net [7:0][1:0]_GEN_21"
ANNOTATION: "RRArbiter mux source mapping proves this exact element is captured tagOp of replay port4. Replay request registers capture only asserted valid initial requests (NodeID1,Size6,aligned64B,normal memory,zero optional profile fields); replay AllowRetry is literal0. Initial-input and its padded aliases remain measured because invalid payload is arbitrary. No routing/TxnID/payload field is excluded."
Toggle _GEN_21 [4][1:0] "net [7:0][1:0]_GEN_21"

CHECKSUM: "3478893755 3492225878"
INSTANCE: retry_tb.dut.output_0
ANNOTATION: "RequestRetry asserted legal request contract: NodeID1, 64-byte aligned access, supported opcodes below64, normal memory (Device=0), PAS/Order/exclusive/tag/multi-request/stash=0, LPID lower5 only. All higher address and arbitrary TxnID/routing bits stay measured."
Toggle io_enq_bits_srcId [6:0] "net io_enq_bits_srcId[6:0]"
Toggle io_enq_bits_stashNidValidEndian "net io_enq_bits_stashNidValidEndian"
Toggle io_enq_bits_opcode [6] "net io_enq_bits_opcode[6:0]"
Toggle io_enq_bits_multiReq "net io_enq_bits_multiReq"
Toggle io_enq_bits_size [5:0] "net io_enq_bits_size[5:0]"
Toggle io_enq_bits_addr [5:0] "net io_enq_bits_addr[43:0]"
Toggle io_enq_bits_pas [2:0] "net io_enq_bits_pas[2:0]"
Toggle io_enq_bits_order [1:0] "net io_enq_bits_order[1:0]"
Toggle io_enq_bits_memAttr [1] "net io_enq_bits_memAttr[3:0]"
Toggle io_enq_bits_lpid [7:5] "net io_enq_bits_lpid[7:0]"
Toggle io_enq_bits_exclSnoopMe "net io_enq_bits_exclSnoopMe"
Toggle io_enq_bits_tagOp [1:0] "net io_enq_bits_tagOp[1:0]"
Toggle io_deq_bits_srcId [6:0] "net io_deq_bits_srcId[6:0]"
Toggle io_deq_bits_stashNidValidEndian "net io_deq_bits_stashNidValidEndian"
Toggle io_deq_bits_opcode [6] "net io_deq_bits_opcode[6:0]"
Toggle io_deq_bits_multiReq "net io_deq_bits_multiReq"
Toggle io_deq_bits_size [5:0] "net io_deq_bits_size[5:0]"
Toggle io_deq_bits_addr [5:0] "net io_deq_bits_addr[43:0]"
Toggle io_deq_bits_pas [2:0] "net io_deq_bits_pas[2:0]"
Toggle io_deq_bits_order [1:0] "net io_deq_bits_order[1:0]"
Toggle io_deq_bits_memAttr [1] "net io_deq_bits_memAttr[3:0]"
Toggle io_deq_bits_lpid [7:5] "net io_deq_bits_lpid[7:0]"
Toggle io_deq_bits_exclSnoopMe "net io_deq_bits_exclSnoopMe"
Toggle io_deq_bits_tagOp [1:0] "net io_deq_bits_tagOp[1:0]"
ANNOTATION: "Output Queue stores the asserted legal RequestRetry request profile. Exact packed positions are read from generated per-field assignments, preserving all full-width address/routing/TxnID and variable attribute bits."
Toggle _ram_ext_R0_data [17:11] "net _ram_ext_R0_data[136:0]"
Toggle _ram_ext_R0_data [37] "net _ram_ext_R0_data[136:0]"
Toggle _ram_ext_R0_data [69:56] "net _ram_ext_R0_data[136:0]"
Toggle _ram_ext_R0_data [110:108] "net _ram_ext_R0_data[136:0]"
Toggle _ram_ext_R0_data [114:113] "net _ram_ext_R0_data[136:0]"
Toggle _ram_ext_R0_data [120] "net _ram_ext_R0_data[136:0]"
Toggle _ram_ext_R0_data [132:129] "net _ram_ext_R0_data[136:0]"
Toggle _ram_ext_R0_data [135:134] "net _ram_ext_R0_data[136:0]"

CHECKSUM: "1565409055 2845470659"
INSTANCE: retry_tb.dut
ANNOTATION: "Only the all-true assertion failure guard is excluded in normal legal protocol traffic: Invalid retry completion-ack profile. Functional gates and assertion remain enabled."
Condition 29 "4177145288" "(_GEN_25 & (io_reqIn_bits_expCompAck != coherentRead)) 1 -1" (3 "11")
ANNOTATION: "Only the all-true assertion failure guard is excluded in normal legal protocol traffic: Invalid retry non-snoop request attributes. Functional gates and assertion remain enabled."
Condition 37 "2137277555" "(io_reqIn_valid & ((~coherent)) & ((~reset)) & ( ~ (((~io_reqIn_bits_memAttr[1])) & ((~io_reqIn_bits_snpAttr))) )) 1 -1" (5 "1111")
ANNOTATION: "Only the all-true assertion failure guard is excluded in normal legal protocol traffic: Invalid retry requester. Functional gates and assertion remain enabled."
Condition 40 "745923699" "(_GEN_25 & (io_reqIn_bits_srcId != 7'b1)) 1 -1" (3 "11")
ANNOTATION: "Only the all-true assertion failure guard is excluded in normal legal protocol traffic: CHI retry requester reused a live TxnID. Functional gates and assertion remain enabled."
Condition 42 "3108172069" "(_GEN_25 & ((|_duplicate_T_12))) 1 -1" (3 "11")
ANNOTATION: "Only the all-true assertion failure guard is excluded in normal legal protocol traffic: Initial CHI request must allow retry without a protocol credit. Functional gates and assertion remain enabled."
Condition 43 "108006917" "(_GEN_25 & ( ~ (io_reqIn_bits_allowRetry & (io_reqIn_bits_pCrdType == 4'b0)) )) 1 -1" (3 "11")
ANNOTATION: "Only the all-true assertion failure guard is excluded in normal legal protocol traffic: Response to wrong retry requester. Functional gates and assertion remain enabled."
Condition 47 "1101780613" "(_GEN_21 & ((~reset)) & (io_rspIn_bits_tgtId != 7'b1)) 1 -1" (4 "111")
ANNOTATION: "Only the all-true assertion failure guard is excluded in normal legal protocol traffic: Response accepted before request reissue. Functional gates and assertion remain enabled."
Condition 56 "3214681341" "(_GEN_30 & ((~grant)) & _GEN_22 & ((|_GEN_23)) & ((~reset)) & (_GEN_28[i_1] == 2'h2)) 1 -1" (7 "111111")
Condition 58 "4231516992" "(io_acceptedData_valid & ((|_GEN_24)) & ((~reset)) & (_GEN_28[i_2] == 2'h2)) 1 -1" (5 "1111")
ANNOTATION: "Only the all-true assertion failure guard is excluded in normal legal protocol traffic: Unsupported CHI retry request opcode. Functional gates and assertion remain enabled."
Condition 14 "2551668066" "(_GEN_25 & ( ~ (coherent | (io_reqIn_bits_opcode == 7'h04) | (io_reqIn_bits_opcode == 7'h1d) | (io_reqIn_bits_opcode == 7'h1c)) )) 1 -1" (3 "11")
ANNOTATION: "Only the all-true assertion failure guard is excluded in normal legal protocol traffic: Unsupported CHI retry request attributes. Functional gates and assertion remain enabled."
Condition 20 "1109361100" "(_GEN_25 & ( ~ (((~io_reqIn_bits_multiReq)) & (io_reqIn_bits_order == 2'b0) & (io_reqIn_bits_size == 6'h06) & (io_reqIn_bits_addr[5:0] == 6'b0) & (io_reqIn_bits_pas == 3'b0) & ((~io_reqIn_bits_exclSnoopMe)) & (io_reqIn_bits_tagOp == 2'b0) & ((~io_reqIn_bits_stashNidValidEndian)) & (io_reqIn_bits_lpid[7:5] == 3'b0)) )) 1 -1" (3 "11")
ANNOTATION: "Only the all-true assertion failure guard is excluded in normal legal protocol traffic: Invalid retry coherent request attributes. Functional gates and assertion remain enabled."
Condition 31 "517468456" "(io_reqIn_valid & coherent & ((~reset)) & ( ~ ((io_reqIn_bits_returnNid == 7'b0) & (io_reqIn_bits_returnTxnId == 12'b0) & (io_reqIn_bits_memAttr == 4'hc) & io_reqIn_bits_snpAttr) )) 1 -1" (5 "1111")
ANNOTATION: "Only the all-true assertion failure guard is excluded in normal legal protocol traffic: Unexpected or repeated RetryAck. Functional gates and assertion remain enabled."
Condition 49 "3899675501" "(_GEN_21 & retryAck & ((~reset)) & ( ~ (((|{((|state_3) & (requests_3_txnId == io_rspIn_bits_txnId)), matches_4_2, matches_4_1, matches_4_0})) & (_GEN_28[i] == 2'b1) & _GEN_29) )) 1 -1" (5 "1111")
ANNOTATION: "Only the all-true assertion failure guard is excluded in normal legal protocol traffic: Excess or errored protocol credit. Functional gates and assertion remain enabled."
Condition 53 "873833217" "(_GEN_30 & grant & ((~reset)) & ( ~ (((|{(((~creditValid_3) | (_GEN_17 & (&credit_3))) | (_GEN_13 ? (((&credit_2) | _GEN_27) | _GEN_26) : (_GEN_27 | _GEN_26))), space_2, space_1, space_0})) & _GEN_29) )) 1 -1" (5 "1111")
ANNOTATION: "RetryAck decodes RSP opcode3, while each selected credit allocation term decodes PCrdGrant opcode7. One opcode cannot be both; exact vector would require both decodes."
Condition 82 "73012043" "(((~_GEN_21)) | retryAck | ((~_GEN_39))) 1 -1" (3 "010")
Condition 83 "379528980" "(((~_GEN_21)) | retryAck | ((~_GEN_40))) 1 -1" (3 "010")
Condition 84 "2400437582" "(((~_GEN_21)) | retryAck | ((~_GEN_41))) 1 -1" (3 "010")
Condition 85 "3656520365" "(((~_GEN_21)) | retryAck | ((~_GEN_42))) 1 -1" (3 "010")
ANNOTATION: "This subexpression is evaluated only in the ternary branch where a later replay port fires. The second term consumes credit through an earlier replay port. RRArbiter grants exactly one output per cycle, so the two replay fires cannot coexist; exact second-only vector is unreachable in this branch."
Condition 97 "3162203369" "(_GEN_7 | _GEN_47) 1 -1" (2 "01")
Condition 102 "2336271217" "(_GEN_9 | _GEN_48) 1 -1" (2 "01")
Condition 107 "1864735692" "(_GEN_11 | _GEN_49) 1 -1" (2 "01")
Condition 112 "167182624" "(((&credit_1)) | _GEN_50) 1 -1" (2 "01")
Condition 141 "1112285567" "(_GEN_18 | _GEN_55) 1 -1" (2 "01")
Condition 148 "3255526067" "(_GEN_19 | _GEN_56) 1 -1" (2 "01")
Condition 155 "2170964985" "(_GEN_20 | _GEN_57) 1 -1" (2 "01")
Condition 162 "2904700612" "(((&credit_3)) | _GEN_58) 1 -1" (2 "01")
ANNOTATION: "Four-entry PriorityEncoder returns fallback index3 when all live-TxnID matches are0. No-match with selected index0,1 or2 is structurally impossible, independent of payload or initialization."
Condition 114 "91711063" "(io_acceptedData_valid & ((|_GEN_24)) & (i_2 == 2'b0)) 1 -1" (2 "101")
Condition 118 "3535129296" "(_GEN_22 & ((|_GEN_23)) & (i_1 == 2'b0)) 1 -1" (2 "101")
Condition 120 "1021694279" "(io_acceptedData_valid & ((|_GEN_24)) & (i_2 == 2'b1)) 1 -1" (2 "101")
Condition 124 "3944017961" "(_GEN_22 & ((|_GEN_23)) & (i_1 == 2'b1)) 1 -1" (2 "101")
Condition 126 "3486384718" "(io_acceptedData_valid & ((|_GEN_24)) & (i_2 == 2'h2)) 1 -1" (2 "101")
Condition 130 "1247087977" "(_GEN_22 & ((|_GEN_23)) & (i_1 == 2'h2)) 1 -1" (2 "101")
ANNOTATION: "Acceptance opcode decode is DBIDResp6/Comp4/CompDBIDResp5; grant is PCrdGrant7. The exact vector requires grant and acceptance simultaneously, impossible for one RSP opcode."
Condition 116 "1348440713" "(grant | ( ~ (_GEN_22 & ((|_GEN_23)) & (i_1 == 2'b0)) )) 1 -1" (3 "10")
Condition 122 "559201839" "(grant | ( ~ (_GEN_22 & ((|_GEN_23)) & (i_1 == 2'b1)) )) 1 -1" (3 "10")
Condition 128 "2154737347" "(grant | ( ~ (_GEN_22 & ((|_GEN_23)) & (i_1 == 2'h2)) )) 1 -1" (3 "10")
Condition 133 "1731676477" "(grant | ( ~ (_GEN_22 & ((|_GEN_23)) & ((&i_1))) )) 1 -1" (3 "10")
ANNOTATION: "Selected credit allocation implies PCrdGrant opcode7, mutually exclusive with RetryAck opcode3. Exact vector requires both opcodes."
Condition 137 "3997230361" "(_GEN_21 & ((~retryAck)) & _GEN_39) 1 -1" (2 "101")
Condition 144 "312808281" "(_GEN_21 & ((~retryAck)) & _GEN_40) 1 -1" (2 "101")
Condition 151 "2618281630" "(_GEN_21 & ((~retryAck)) & _GEN_41) 1 -1" (2 "101")
Condition 158 "3436279767" "(_GEN_21 & ((~retryAck)) & _GEN_42) 1 -1" (2 "101")
ANNOTATION: "This ternary branch is selected by replay port3 fire. Its earlier-port consumption terms require another replay fire in the same cycle, forbidden by the single-output RRArbiter. Exact earlier-only vectors are unreachable; current-port selection remains measured."
Condition 272 "1429792695" "(_GEN_14 | _GEN_8 | _GEN_1) 1 -1" (2 "001")
Condition 272 "1429792695" "(_GEN_14 | _GEN_8 | _GEN_1) 1 -1" (3 "010")
Condition 277 "3581322673" "(_GEN_15 | _GEN_10 | _GEN_3) 1 -1" (2 "001")
Condition 277 "3581322673" "(_GEN_15 | _GEN_10 | _GEN_3) 1 -1" (3 "010")
Condition 282 "3852876295" "(_GEN_16 | _GEN_12 | _GEN_5) 1 -1" (2 "001")
Condition 282 "3852876295" "(_GEN_16 | _GEN_12 | _GEN_5) 1 -1" (3 "010")

CHECKSUM: "917436931 1648997668"
INSTANCE: retry_tb.dut.arb
ANNOTATION: "Replay port4 becomes live only after its slot was accepted through initial port0. A port4 grant changes that slot to reissued and removes its valid immediately. Before port4 can become valid again, an initial port0 grant is mandatory and sets lastGrant0. Other intervening grants are ports1..3. Thus live port4 cannot coexist with lastGrant4; values5..7 cannot survive the required initial grant either."
Condition 6 "1359597920" "(io_in_4_valid & ((~ctrl_validMask_grantMask_lastGrant[2]))) 1 -1" (2 "10")
