`ifndef CHI_RETRY_TB
`define CHI_RETRY_TB retry_tb
`endif
module `CHI_RETRY_TB;
  import uvm_pkg::*;
  import chi_retry_pkg::*;
  logic clock = 0;
  always #5 clock = ~clock;
  chi_retry_if source_if (clock);
  RequestRetry dut (
      .clock(clock),
      .reset(source_if.reset),
      .io_reqIn_valid(source_if.req_in_valid),
      .io_reqIn_ready(source_if.req_in_ready),
      .io_reqIn_bits_qos(source_if.req_in[3:0]),
      .io_reqIn_bits_tgtId(source_if.req_in[10:4]),
      .io_reqIn_bits_srcId(source_if.req_in[17:11]),
      .io_reqIn_bits_txnId(source_if.req_in[29:18]),
      .io_reqIn_bits_returnNid(source_if.req_in[36:30]),
      .io_reqIn_bits_stashNidValidEndian(source_if.req_in[37:37]),
      .io_reqIn_bits_returnTxnId(source_if.req_in[49:38]),
      .io_reqIn_bits_opcode(source_if.req_in[56:50]),
      .io_reqIn_bits_multiReq(source_if.req_in[57:57]),
      .io_reqIn_bits_size(source_if.req_in[63:58]),
      .io_reqIn_bits_addr(source_if.req_in[107:64]),
      .io_reqIn_bits_pas(source_if.req_in[110:108]),
      .io_reqIn_bits_likelyShared(source_if.req_in[111:111]),
      .io_reqIn_bits_allowRetry(source_if.req_in[112:112]),
      .io_reqIn_bits_order(source_if.req_in[114:113]),
      .io_reqIn_bits_pCrdType(source_if.req_in[118:115]),
      .io_reqIn_bits_memAttr(source_if.req_in[122:119]),
      .io_reqIn_bits_snpAttr(source_if.req_in[123:123]),
      .io_reqIn_bits_lpid(source_if.req_in[131:124]),
      .io_reqIn_bits_exclSnoopMe(source_if.req_in[132:132]),
      .io_reqIn_bits_expCompAck(source_if.req_in[133:133]),
      .io_reqIn_bits_tagOp(source_if.req_in[135:134]),
      .io_reqIn_bits_traceTag(source_if.req_in[136:136]),
      .io_reqOut_valid(source_if.req_out_valid),
      .io_reqOut_ready(source_if.req_out_ready),
      .io_reqOut_bits_qos(source_if.req_out[3:0]),
      .io_reqOut_bits_tgtId(source_if.req_out[10:4]),
      .io_reqOut_bits_srcId(source_if.req_out[17:11]),
      .io_reqOut_bits_txnId(source_if.req_out[29:18]),
      .io_reqOut_bits_returnNid(source_if.req_out[36:30]),
      .io_reqOut_bits_stashNidValidEndian(source_if.req_out[37:37]),
      .io_reqOut_bits_returnTxnId(source_if.req_out[49:38]),
      .io_reqOut_bits_opcode(source_if.req_out[56:50]),
      .io_reqOut_bits_multiReq(source_if.req_out[57:57]),
      .io_reqOut_bits_size(source_if.req_out[63:58]),
      .io_reqOut_bits_addr(source_if.req_out[107:64]),
      .io_reqOut_bits_pas(source_if.req_out[110:108]),
      .io_reqOut_bits_likelyShared(source_if.req_out[111:111]),
      .io_reqOut_bits_allowRetry(source_if.req_out[112:112]),
      .io_reqOut_bits_order(source_if.req_out[114:113]),
      .io_reqOut_bits_pCrdType(source_if.req_out[118:115]),
      .io_reqOut_bits_memAttr(source_if.req_out[122:119]),
      .io_reqOut_bits_snpAttr(source_if.req_out[123:123]),
      .io_reqOut_bits_lpid(source_if.req_out[131:124]),
      .io_reqOut_bits_exclSnoopMe(source_if.req_out[132:132]),
      .io_reqOut_bits_expCompAck(source_if.req_out[133:133]),
      .io_reqOut_bits_tagOp(source_if.req_out[135:134]),
      .io_reqOut_bits_traceTag(source_if.req_out[136:136]),
      .io_rspIn_valid(source_if.rsp_in_valid),
      .io_rspIn_ready(source_if.rsp_in_ready),
      .io_rspIn_bits_qos(source_if.rsp_in[3:0]),
      .io_rspIn_bits_tgtId(source_if.rsp_in[10:4]),
      .io_rspIn_bits_srcId(source_if.rsp_in[17:11]),
      .io_rspIn_bits_txnId(source_if.rsp_in[29:18]),
      .io_rspIn_bits_opcode(source_if.rsp_in[34:30]),
      .io_rspIn_bits_respErr(source_if.rsp_in[36:35]),
      .io_rspIn_bits_resp(source_if.rsp_in[39:37]),
      .io_rspIn_bits_fwdState(source_if.rsp_in[42:40]),
      .io_rspIn_bits_cBusy(source_if.rsp_in[45:43]),
      .io_rspIn_bits_dbid(source_if.rsp_in[57:46]),
      .io_rspIn_bits_pCrdType(source_if.rsp_in[61:58]),
      .io_rspIn_bits_tagOp(source_if.rsp_in[63:62]),
      .io_rspIn_bits_traceTag(source_if.rsp_in[64:64]),
      .io_rspIn_bits_cacheLineId(source_if.rsp_in[70:65]),
      .io_rspOut_valid(source_if.rsp_out_valid),
      .io_rspOut_ready(source_if.rsp_out_ready),
      .io_rspOut_bits_qos(source_if.rsp_out[3:0]),
      .io_rspOut_bits_tgtId(source_if.rsp_out[10:4]),
      .io_rspOut_bits_srcId(source_if.rsp_out[17:11]),
      .io_rspOut_bits_txnId(source_if.rsp_out[29:18]),
      .io_rspOut_bits_opcode(source_if.rsp_out[34:30]),
      .io_rspOut_bits_respErr(source_if.rsp_out[36:35]),
      .io_rspOut_bits_resp(source_if.rsp_out[39:37]),
      .io_rspOut_bits_fwdState(source_if.rsp_out[42:40]),
      .io_rspOut_bits_cBusy(source_if.rsp_out[45:43]),
      .io_rspOut_bits_dbid(source_if.rsp_out[57:46]),
      .io_rspOut_bits_pCrdType(source_if.rsp_out[61:58]),
      .io_rspOut_bits_tagOp(source_if.rsp_out[63:62]),
      .io_rspOut_bits_traceTag(source_if.rsp_out[64:64]),
      .io_rspOut_bits_cacheLineId(source_if.rsp_out[70:65]),
      .io_acceptedData_valid(source_if.accepted_valid),
      .io_acceptedData_bits_srcId(source_if.accepted_src),
      .io_acceptedData_bits_txnId(source_if.accepted_txn),
      .io_pending(source_if.pending)
  );
  initial begin
    uvm_config_db#(virtual chi_retry_if)::set(null, "uvm_test_top", "vif", source_if);
    run_test("protocol_test");
  end
endmodule
