// Format Version: 2
// Reviewed for 2 CPUs, 4 MSHRs, 4 sets, 2 ways, 64-byte lines, 256-bit CHI data.

CHECKSUM: "848348206 1645746301"
INSTANCE: coherence_tb.dut.cache
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Unknown Cache operation"
Block 10 "1190204013" "if (1)"
Block 11 "3885794289" "$error(\"Assertion failed: Unknown Cache operation\n    at Cache.scala:73 assert(req.op <= CacheOp.Invalidate.U, \\"Unknown Cache operation\\")\n\");"
Block 13 "1190204013" "if (1)"
Block 14 "3662014904" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Cache operations require a line-aligned address"
Block 18 "1317833989" "if (1)"
Block 19 "1722205720" "$error(\"Assertion failed: Cache operations require a line-aligned address\n    at Cache.scala:74 assert(req.addr(p.offsetBits - 1, 0) === 0.U, \\"Cache operations require a line-aligned address\\")\n\");"
Block 21 "1317833989" "if (1)"
Block 22 "505164254" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Duplicate Cache tag"
Block 26 "3036749987" "if (1)"
Block 27 "2991635828" "$error(\"Assertion failed: Duplicate Cache tag\n    at Cache.scala:76 assert(PopCount(hits) <= 1.U, \\"Duplicate Cache tag\\")\n\");"
Block 29 "3036749987" "if (1)"
Block 30 "3772797571" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Cache fill would create a duplicate tag"
Block 34 "3744269243" "if (1)"
Block 35 "987059305" "$error(\"Assertion failed: Cache fill would create a duplicate tag\n    at Cache.scala:89 assert(!hits.orR || hits(req.way), \\"Cache fill would create a duplicate tag\\")\n\");"
Block 37 "3744269243" "if (1)"
Block 38 "629733424" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Cache write requires the matching resident line"
Block 42 "4266678685" "if (1)"
Block 43 "4034066179" "$error(\"Assertion failed: Cache write requires the matching resident line\n    at Cache.scala:99 assert(entryValid && hits(req.way), \\"Cache write requires the matching resident line\\")\n\");"
Block 45 "4266678685" "if (1)"
Block 46 "1550685438" "$fatal;"

CHECKSUM: "25866875 2457151256"
INSTANCE: coherence_tb.dut.directory
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Multiple transactions update one directory entry"
Block 2 "2664146107" "if (1)"
Block 3 "3533917897" "$error(\"Assertion failed: Multiple transactions update one directory entry\n    at Directory.scala:43 assert(PopCount(writers) <= 1.U, \\"Multiple transactions update one directory entry\\")\n\");"
Block 5 "2664146107" "if (1)"
Block 6 "3472375403" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Unique ownership requires exactly one CPU"
Block 10 "2881929055" "if (1)"
Block 11 "995660494" "$error(\"Assertion failed: Unique ownership requires exactly one CPU\n    at Directory.scala:46 assert(!next.unique || PopCount(next.sharers) === 1.U, \\"Unique ownership requires exactly one CPU\\")\n\");"
Block 13 "2881929055" "if (1)"
Block 14 "1126102520" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Multiple transactions update one directory entry"
Block 18 "1723217575" "if (1)"
Block 19 "3904278350" "$error(\"Assertion failed: Multiple transactions update one directory entry\n    at Directory.scala:43 assert(PopCount(writers) <= 1.U, \\"Multiple transactions update one directory entry\\")\n\");"
Block 21 "1723217575" "if (1)"
Block 22 "4109238252" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Unique ownership requires exactly one CPU"
Block 26 "3405939620" "if (1)"
Block 27 "684207841" "$error(\"Assertion failed: Unique ownership requires exactly one CPU\n    at Directory.scala:46 assert(!next.unique || PopCount(next.sharers) === 1.U, \\"Unique ownership requires exactly one CPU\\")\n\");"
Block 29 "3405939620" "if (1)"
Block 30 "1351502295" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Multiple transactions update one directory entry"
Block 34 "3919299312" "if (1)"
Block 35 "2315541197" "$error(\"Assertion failed: Multiple transactions update one directory entry\n    at Directory.scala:43 assert(PopCount(writers) <= 1.U, \\"Multiple transactions update one directory entry\\")\n\");"
Block 37 "3919299312" "if (1)"
Block 38 "2522819183" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Unique ownership requires exactly one CPU"
Block 42 "539207809" "if (1)"
Block 43 "2227510213" "$error(\"Assertion failed: Unique ownership requires exactly one CPU\n    at Directory.scala:46 assert(!next.unique || PopCount(next.sharers) === 1.U, \\"Unique ownership requires exactly one CPU\\")\n\");"
Block 45 "539207809" "if (1)"
Block 46 "4236475635" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Multiple transactions update one directory entry"
Block 50 "4085285969" "if (1)"
Block 51 "2434010258" "$error(\"Assertion failed: Multiple transactions update one directory entry\n    at Directory.scala:43 assert(PopCount(writers) <= 1.U, \\"Multiple transactions update one directory entry\\")\n\");"
Block 53 "4085285969" "if (1)"
Block 54 "2370796592" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Unique ownership requires exactly one CPU"
Block 58 "3010328178" "if (1)"
Block 59 "839440352" "$error(\"Assertion failed: Unique ownership requires exactly one CPU\n    at Directory.scala:46 assert(!next.unique || PopCount(next.sharers) === 1.U, \\"Unique ownership requires exactly one CPU\\")\n\");"
Block 61 "3010328178" "if (1)"
Block 62 "1246671062" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Multiple transactions update one directory entry"
Block 66 "2091741190" "if (1)"
Block 67 "4087798033" "$error(\"Assertion failed: Multiple transactions update one directory entry\n    at Directory.scala:43 assert(PopCount(writers) <= 1.U, \\"Multiple transactions update one directory entry\\")\n\");"
Block 69 "2091741190" "if (1)"
Block 70 "4026378675" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Unique ownership requires exactly one CPU"
Block 74 "2992832868" "if (1)"
Block 75 "730445366" "$error(\"Assertion failed: Unique ownership requires exactly one CPU\n    at Directory.scala:46 assert(!next.unique || PopCount(next.sharers) === 1.U, \\"Unique ownership requires exactly one CPU\\")\n\");"
Block 77 "2992832868" "if (1)"
Block 78 "1406128384" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Multiple transactions update one directory entry"
Block 82 "2228281882" "if (1)"
Block 83 "3383957654" "$error(\"Assertion failed: Multiple transactions update one directory entry\n    at Directory.scala:43 assert(PopCount(writers) <= 1.U, \\"Multiple transactions update one directory entry\\")\n\");"
Block 85 "2228281882" "if (1)"
Block 86 "3588778036" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Unique ownership requires exactly one CPU"
Block 90 "3031124909" "if (1)"
Block 91 "4279530673" "$error(\"Assertion failed: Unique ownership requires exactly one CPU\n    at Directory.scala:46 assert(!next.unique || PopCount(next.sharers) === 1.U, \\"Unique ownership requires exactly one CPU\\")\n\");"
Block 93 "3031124909" "if (1)"
Block 94 "2270303111" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Multiple transactions update one directory entry"
Block 98 "201135693" "if (1)"
Block 99 "2869021973" "$error(\"Assertion failed: Multiple transactions update one directory entry\n    at Directory.scala:43 assert(PopCount(writers) <= 1.U, \\"Multiple transactions update one directory entry\\")\n\");"
Block 101 "201135693" "if (1)"
Block 102 "3076177335" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Unique ownership requires exactly one CPU"
Block 106 "3770691673" "if (1)"
Block 107 "389918641" "$error(\"Assertion failed: Unique ownership requires exactly one CPU\n    at Directory.scala:46 assert(!next.unique || PopCount(next.sharers) === 1.U, \\"Unique ownership requires exactly one CPU\\")\n\");"
Block 109 "3770691673" "if (1)"
Block 110 "1870383239" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Multiple transactions update one directory entry"
Block 114 "3662072233" "if (1)"
Block 115 "3809633553" "$error(\"Assertion failed: Multiple transactions update one directory entry\n    at Directory.scala:43 assert(PopCount(writers) <= 1.U, \\"Multiple transactions update one directory entry\\")\n\");"
Block 117 "3662072233" "if (1)"
Block 118 "4282979763" "$fatal;"
ANNOTATION: "Assertion-failure diagnostic only; assertion remains enabled: Unique ownership requires exactly one CPU"
Block 122 "1829712518" "if (1)"
Block 123 "4024367402" "$error(\"Assertion failed: Unique ownership requires exactly one CPU\n    at Directory.scala:46 assert(!next.unique || PopCount(next.sharers) === 1.U, \\"Unique ownership requires exactly one CPU\\")\n\");"
Block 125 "1829712518" "if (1)"
Block 126 "2543361564" "$fatal;"

CHECKSUM: "3226703875 2930150559"
INSTANCE: coherence_tb.dut.cache.responses
ANNOTATION: "Source-proven Home profile: MSHR IDs 0..3, requester IDs 1..2, aligned 64-byte addresses, full-line masks, all ways eligible, dirty metadata bit 0; CHI optional fields are assigned constants. Only the specified constant bits are excluded."
Toggle io_enq_bits_id [7:2] "net io_enq_bits_id[7:0]"
Toggle io_enq_bits_available "net io_enq_bits_available"
Toggle io_enq_bits_addr [5:0] "net io_enq_bits_addr[43:0]"
Toggle io_enq_bits_metadata [3:1] "net io_enq_bits_metadata[3:0]"
Toggle io_deq_bits_id [7:2] "net io_deq_bits_id[7:0]"
Toggle io_deq_bits_available "net io_deq_bits_available"
Toggle io_deq_bits_addr [5:0] "net io_deq_bits_addr[43:0]"
Toggle io_deq_bits_metadata [3:1] "net io_deq_bits_metadata[3:0]"

CHECKSUM: "1696518855 210682840"
INSTANCE: coherence_tb.dut.datQueue
ANNOTATION: "Source-proven Home profile: MSHR IDs 0..3, requester IDs 1..2, aligned 64-byte addresses, full-line masks, all ways eligible, dirty metadata bit 0; CHI optional fields are assigned constants. Only the specified constant bits are excluded."
Toggle io_enq_bits_tgtId [6:2] "net io_enq_bits_tgtId[6:0]"
Toggle io_enq_bits_resp [2] "net io_enq_bits_resp[2:0]"
Toggle io_enq_bits_dbid [15:2] "net io_enq_bits_dbid[15:0]"
Toggle io_enq_bits_dataId [0] "net io_enq_bits_dataId[1:0]"
Toggle io_deq_bits_qos [3:0] "net io_deq_bits_qos[3:0]"
Toggle io_deq_bits_tgtId [6:2] "net io_deq_bits_tgtId[6:0]"
Toggle io_deq_bits_srcId [6:0] "net io_deq_bits_srcId[6:0]"
Toggle io_deq_bits_homeNid [6:0] "net io_deq_bits_homeNid[6:0]"
Toggle io_deq_bits_opcode [3:0] "net io_deq_bits_opcode[3:0]"
Toggle io_deq_bits_resp [2] "net io_deq_bits_resp[2:0]"
Toggle io_deq_bits_dataSource [7:0] "net io_deq_bits_dataSource[7:0]"
Toggle io_deq_bits_dataPull "net io_deq_bits_dataPull"
Toggle io_deq_bits_cBusy [2:0] "net io_deq_bits_cBusy[2:0]"
Toggle io_deq_bits_dbid [15:2] "net io_deq_bits_dbid[15:0]"
Toggle io_deq_bits_ccid [1:0] "net io_deq_bits_ccid[1:0]"
Toggle io_deq_bits_dataId [0] "net io_deq_bits_dataId[1:0]"
Toggle io_deq_bits_cacheLineId [5:0] "net io_deq_bits_cacheLineId[5:0]"
Toggle io_deq_bits_tagOp [1:0] "net io_deq_bits_tagOp[1:0]"
Toggle io_deq_bits_tag [7:0] "net io_deq_bits_tag[7:0]"
Toggle io_deq_bits_tagUpdate [1:0] "net io_deq_bits_tagUpdate[1:0]"
Toggle io_deq_bits_traceTag "net io_deq_bits_traceTag"
Toggle io_deq_bits_copyAtHome "net io_deq_bits_copyAtHome"
Toggle io_deq_bits_numDat [1:0] "net io_deq_bits_numDat[1:0]"
Toggle io_deq_bits_replicate "net io_deq_bits_replicate"

CHECKSUM: "1414150944 1331432527"
INSTANCE: coherence_tb.dut.cacheQueue
ANNOTATION: "Source-proven Home profile: MSHR IDs 0..3, requester IDs 1..2, aligned 64-byte addresses, full-line masks, all ways eligible, dirty metadata bit 0; CHI optional fields are assigned constants. Only the specified constant bits are excluded."
Toggle io_enq_bits_id [7:2] "net io_enq_bits_id[7:0]"
Toggle io_enq_bits_addr [5:0] "net io_enq_bits_addr[43:0]"
Toggle io_enq_bits_metadata [3:1] "net io_enq_bits_metadata[3:0]"
Toggle io_deq_bits_id [7:2] "net io_deq_bits_id[7:0]"
Toggle io_deq_bits_addr [5:0] "net io_deq_bits_addr[43:0]"
Toggle io_deq_bits_mask [63:0] "net io_deq_bits_mask[63:0]"
Toggle io_deq_bits_metadata [3:1] "net io_deq_bits_metadata[3:0]"
Toggle io_deq_bits_eligible [1:0] "net io_deq_bits_eligible[1:0]"

CHECKSUM: "3112608224 3447389693"
INSTANCE: coherence_tb.dut.memQueue
ANNOTATION: "Source-proven Home profile: MSHR IDs 0..3, requester IDs 1..2, aligned 64-byte addresses, full-line masks, all ways eligible, dirty metadata bit 0; CHI optional fields are assigned constants. Only the specified constant bits are excluded."
Toggle io_enq_bits_id [11:2] "net io_enq_bits_id[11:0]"
Toggle io_enq_bits_addr [5:0] "net io_enq_bits_addr[43:0]"
Toggle io_deq_bits_id [11:2] "net io_deq_bits_id[11:0]"
Toggle io_deq_bits_addr [5:0] "net io_deq_bits_addr[43:0]"
Toggle io_deq_bits_mask [63:0] "net io_deq_bits_mask[63:0]"

CHECKSUM: "769480049 1064374571"
INSTANCE: coherence_tb.dut.rspQueue
ANNOTATION: "Source-proven Home profile: MSHR IDs 0..3, requester IDs 1..2, aligned 64-byte addresses, full-line masks, all ways eligible, dirty metadata bit 0; CHI optional fields are assigned constants. Only the specified constant bits are excluded."
Toggle io_enq_bits_tgtId [6:2] "net io_enq_bits_tgtId[6:0]"
Toggle io_enq_bits_opcode [4:1] "net io_enq_bits_opcode[4:0]"
Toggle io_enq_bits_dbid [11:2] "net io_enq_bits_dbid[11:0]"
Toggle io_deq_bits_qos [3:0] "net io_deq_bits_qos[3:0]"
Toggle io_deq_bits_tgtId [6:2] "net io_deq_bits_tgtId[6:0]"
Toggle io_deq_bits_srcId [6:0] "net io_deq_bits_srcId[6:0]"
Toggle io_deq_bits_opcode [4:1] "net io_deq_bits_opcode[4:0]"
Toggle io_deq_bits_resp [2:0] "net io_deq_bits_resp[2:0]"
Toggle io_deq_bits_fwdState [2:0] "net io_deq_bits_fwdState[2:0]"
Toggle io_deq_bits_cBusy [2:0] "net io_deq_bits_cBusy[2:0]"
Toggle io_deq_bits_dbid [11:2] "net io_deq_bits_dbid[11:0]"
Toggle io_deq_bits_pCrdType [3:0] "net io_deq_bits_pCrdType[3:0]"
Toggle io_deq_bits_tagOp [1:0] "net io_deq_bits_tagOp[1:0]"
Toggle io_deq_bits_traceTag "net io_deq_bits_traceTag"
Toggle io_deq_bits_cacheLineId [5:0] "net io_deq_bits_cacheLineId[5:0]"

CHECKSUM: "2391098903 4025403226"
INSTANCE: coherence_tb.dut.snpQueue
ANNOTATION: "Source-proven Home profile: MSHR IDs 0..3, requester IDs 1..2, aligned 64-byte addresses, full-line masks, all ways eligible, dirty metadata bit 0; CHI optional fields are assigned constants. Only the specified constant bits are excluded."
Toggle io_enq_bits_targetNode [6:2] "net io_enq_bits_targetNode[6:0]"
Toggle io_enq_bits_flit_txnId [11:2] "net io_enq_bits_flit_txnId[11:0]"
Toggle io_enq_bits_flit_opcode [4] "net io_enq_bits_flit_opcode[4:0]"
Toggle io_enq_bits_flit_addr [2:0] "net io_enq_bits_flit_addr[40:0]"
Toggle io_deq_bits_targetNode [6:2] "net io_deq_bits_targetNode[6:0]"
Toggle io_deq_bits_flit_qos [3:0] "net io_deq_bits_flit_qos[3:0]"
Toggle io_deq_bits_flit_srcId [6:0] "net io_deq_bits_flit_srcId[6:0]"
Toggle io_deq_bits_flit_txnId [11:2] "net io_deq_bits_flit_txnId[11:0]"
Toggle io_deq_bits_flit_fwdNid [6:0] "net io_deq_bits_flit_fwdNid[6:0]"
Toggle io_deq_bits_flit_fwdTxnId [11:0] "net io_deq_bits_flit_fwdTxnId[11:0]"
Toggle io_deq_bits_flit_opcode [4] "net io_deq_bits_flit_opcode[4:0]"
Toggle io_deq_bits_flit_addr [2:0] "net io_deq_bits_flit_addr[40:0]"
Toggle io_deq_bits_flit_pas [2:0] "net io_deq_bits_flit_pas[2:0]"
Toggle io_deq_bits_flit_doNotGoToSd "net io_deq_bits_flit_doNotGoToSd"
Toggle io_deq_bits_flit_traceTag "net io_deq_bits_flit_traceTag"

CHECKSUM: "1853676028 3335661445"
INSTANCE: coherence_tb.dut.cacheArb
ANNOTATION: "Source-proven Home profile: MSHR IDs 0..3, requester IDs 1..2, aligned 64-byte addresses, full-line masks, all ways eligible, dirty metadata bit 0; CHI optional fields are assigned constants. Only the specified constant bits are excluded."
Toggle io_in_0_bits_addr [5:0] "net io_in_0_bits_addr[43:0]"
Toggle io_in_0_bits_metadata [3:1] "net io_in_0_bits_metadata[3:0]"
Toggle io_in_1_bits_addr [5:0] "net io_in_1_bits_addr[43:0]"
Toggle io_in_1_bits_metadata [3:1] "net io_in_1_bits_metadata[3:0]"
Toggle io_in_2_bits_addr [5:0] "net io_in_2_bits_addr[43:0]"
Toggle io_in_2_bits_metadata [3:1] "net io_in_2_bits_metadata[3:0]"
Toggle io_in_3_bits_addr [5:0] "net io_in_3_bits_addr[43:0]"
Toggle io_in_3_bits_metadata [3:1] "net io_in_3_bits_metadata[3:0]"
Toggle io_out_bits_id [7:2] "net io_out_bits_id[7:0]"
Toggle io_out_bits_addr [5:0] "net io_out_bits_addr[43:0]"
Toggle io_out_bits_metadata [3:1] "net io_out_bits_metadata[3:0]"

CHECKSUM: "3130163852 2143613990"
INSTANCE: coherence_tb.dut.memArb
ANNOTATION: "Source-proven Home profile: MSHR IDs 0..3, requester IDs 1..2, aligned 64-byte addresses, full-line masks, all ways eligible, dirty metadata bit 0; CHI optional fields are assigned constants. Only the specified constant bits are excluded."
Toggle io_in_0_bits_addr [5:0] "net io_in_0_bits_addr[43:0]"
Toggle io_in_1_bits_addr [5:0] "net io_in_1_bits_addr[43:0]"
Toggle io_in_2_bits_addr [5:0] "net io_in_2_bits_addr[43:0]"
Toggle io_in_3_bits_addr [5:0] "net io_in_3_bits_addr[43:0]"
Toggle io_out_bits_id [11:2] "net io_out_bits_id[11:0]"
Toggle io_out_bits_addr [5:0] "net io_out_bits_addr[43:0]"

CHECKSUM: "3716118738 1796417120"
INSTANCE: coherence_tb.dut.snpArb
ANNOTATION: "Source-proven Home profile: MSHR IDs 0..3, requester IDs 1..2, aligned 64-byte addresses, full-line masks, all ways eligible, dirty metadata bit 0; CHI optional fields are assigned constants. Only the specified constant bits are excluded."
Toggle io_in_0_bits_targetNode [6:2] "net io_in_0_bits_targetNode[6:0]"
Toggle io_in_0_bits_flit_opcode [4] "net io_in_0_bits_flit_opcode[4:0]"
Toggle io_in_0_bits_flit_addr [2:0] "net io_in_0_bits_flit_addr[40:0]"
Toggle io_in_1_bits_targetNode [6:2] "net io_in_1_bits_targetNode[6:0]"
Toggle io_in_1_bits_flit_opcode [4] "net io_in_1_bits_flit_opcode[4:0]"
Toggle io_in_1_bits_flit_addr [2:0] "net io_in_1_bits_flit_addr[40:0]"
Toggle io_in_2_bits_targetNode [6:2] "net io_in_2_bits_targetNode[6:0]"
Toggle io_in_2_bits_flit_opcode [4] "net io_in_2_bits_flit_opcode[4:0]"
Toggle io_in_2_bits_flit_addr [2:0] "net io_in_2_bits_flit_addr[40:0]"
Toggle io_in_3_bits_targetNode [6:2] "net io_in_3_bits_targetNode[6:0]"
Toggle io_in_3_bits_flit_opcode [4] "net io_in_3_bits_flit_opcode[4:0]"
Toggle io_in_3_bits_flit_addr [2:0] "net io_in_3_bits_flit_addr[40:0]"
Toggle io_out_bits_targetNode [6:2] "net io_out_bits_targetNode[6:0]"
Toggle io_out_bits_flit_txnId [11:2] "net io_out_bits_flit_txnId[11:0]"
Toggle io_out_bits_flit_opcode [4] "net io_out_bits_flit_opcode[4:0]"
Toggle io_out_bits_flit_addr [2:0] "net io_out_bits_flit_addr[40:0]"

CHECKSUM: "2004716196 3529883256"
INSTANCE: coherence_tb.dut.rspArb
ANNOTATION: "Source-proven Home profile: MSHR IDs 0..3, requester IDs 1..2, aligned 64-byte addresses, full-line masks, all ways eligible, dirty metadata bit 0; CHI optional fields are assigned constants. Only the specified constant bits are excluded."
Toggle io_in_0_bits_tgtId [6:2] "net io_in_0_bits_tgtId[6:0]"
Toggle io_in_0_bits_opcode [4:1] "net io_in_0_bits_opcode[4:0]"
Toggle io_in_1_bits_tgtId [6:2] "net io_in_1_bits_tgtId[6:0]"
Toggle io_in_1_bits_opcode [4:1] "net io_in_1_bits_opcode[4:0]"
Toggle io_in_2_bits_tgtId [6:2] "net io_in_2_bits_tgtId[6:0]"
Toggle io_in_2_bits_opcode [4:1] "net io_in_2_bits_opcode[4:0]"
Toggle io_in_3_bits_tgtId [6:2] "net io_in_3_bits_tgtId[6:0]"
Toggle io_in_3_bits_opcode [4:1] "net io_in_3_bits_opcode[4:0]"
Toggle io_out_bits_tgtId [6:2] "net io_out_bits_tgtId[6:0]"
Toggle io_out_bits_opcode [4:1] "net io_out_bits_opcode[4:0]"
Toggle io_out_bits_dbid [11:2] "net io_out_bits_dbid[11:0]"

CHECKSUM: "3496838959 3135397854"
INSTANCE: coherence_tb.dut.datArb
ANNOTATION: "Source-proven Home profile: MSHR IDs 0..3, requester IDs 1..2, aligned 64-byte addresses, full-line masks, all ways eligible, dirty metadata bit 0; CHI optional fields are assigned constants. Only the specified constant bits are excluded."
Toggle io_in_0_bits_tgtId [6:2] "net io_in_0_bits_tgtId[6:0]"
Toggle io_in_0_bits_resp [2] "net io_in_0_bits_resp[2:0]"
Toggle io_in_0_bits_dataId [0] "net io_in_0_bits_dataId[1:0]"
Toggle io_in_1_bits_tgtId [6:2] "net io_in_1_bits_tgtId[6:0]"
Toggle io_in_1_bits_resp [2] "net io_in_1_bits_resp[2:0]"
Toggle io_in_1_bits_dataId [0] "net io_in_1_bits_dataId[1:0]"
Toggle io_in_2_bits_tgtId [6:2] "net io_in_2_bits_tgtId[6:0]"
Toggle io_in_2_bits_resp [2] "net io_in_2_bits_resp[2:0]"
Toggle io_in_2_bits_dataId [0] "net io_in_2_bits_dataId[1:0]"
Toggle io_in_3_bits_tgtId [6:2] "net io_in_3_bits_tgtId[6:0]"
Toggle io_in_3_bits_resp [2] "net io_in_3_bits_resp[2:0]"
Toggle io_in_3_bits_dataId [0] "net io_in_3_bits_dataId[1:0]"
Toggle io_out_bits_tgtId [6:2] "net io_out_bits_tgtId[6:0]"
Toggle io_out_bits_resp [2] "net io_out_bits_resp[2:0]"
Toggle io_out_bits_dbid [15:2] "net io_out_bits_dbid[15:0]"
Toggle io_out_bits_dataId [0] "net io_out_bits_dataId[1:0]"

CHECKSUM: "848348206 843507997"
INSTANCE: coherence_tb.dut.cache
ANNOTATION: "Source-proven Home profile: MSHR IDs 0..3, requester IDs 1..2, aligned 64-byte addresses, full-line masks, all ways eligible, dirty metadata bit 0; CHI optional fields are assigned constants. Only the specified constant bits are excluded."
Toggle io_request_bits_id [7:2] "net io_request_bits_id[7:0]"
Toggle io_request_bits_addr [5:0] "net io_request_bits_addr[43:0]"
Toggle io_request_bits_mask [63:0] "net io_request_bits_mask[63:0]"
Toggle io_request_bits_metadata [3:1] "net io_request_bits_metadata[3:0]"
Toggle io_request_bits_eligible [1:0] "net io_request_bits_eligible[1:0]"
Toggle io_response_bits_id [7:2] "net io_response_bits_id[7:0]"
Toggle io_response_bits_available "net io_response_bits_available"
Toggle io_response_bits_addr [5:0] "net io_response_bits_addr[43:0]"
Toggle io_response_bits_metadata [3:1] "net io_response_bits_metadata[3:0]"
Toggle metadata_0_0 [3:1] "reg metadata_0_0[3:0]"
Toggle metadata_0_1 [3:1] "reg metadata_0_1[3:0]"
Toggle metadata_0_2 [3:1] "reg metadata_0_2[3:0]"
Toggle metadata_0_3 [3:1] "reg metadata_0_3[3:0]"
Toggle metadata_1_0 [3:1] "reg metadata_1_0[3:0]"
Toggle metadata_1_1 [3:1] "reg metadata_1_1[3:0]"
Toggle metadata_1_2 [3:1] "reg metadata_1_2[3:0]"
Toggle metadata_1_3 [3:1] "reg metadata_1_3[3:0]"
Toggle result_id [7:2] "reg result_id[7:0]"
Toggle result_addr [5:0] "reg result_addr[43:0]"
Toggle result_metadata [3:1] "reg result_metadata[3:0]"
