+incdir+@VERIFY@/uvm/src/ip
+incdir+@RTL@
+incdir+@RESOURCES@
@VERIFY@/uvm/src/ip/package.sv
@VERIFY@/uvm/src/ip/stream_if.sv
@RESOURCES@/interface.sv
@RESOURCES@/package.sv
@RTL@/Coherence.sv
@RESOURCES@/coherence_tb.sv
