# 防止pre-commit检查未暂存的文件
exclude: ^$
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.3
    hooks:
      - id: clang-format
        name: clang-format C++ code
        files: \.(cpp|hpp|cc|cxx|h|c|hxx)$
        args: [--style=llvm]

  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        language_version: python3.10
        args:
          - --style={based_on_style:pep8, indent_width:2, column_limit:200}

  # a comprehensive tool for checking the style and quality of Python code.
  # It combines three popular Python tools:
  # PyFlakes: Checks for logical errors in the code.
  # pycodestyle (formerly known as pep8): Checks for adherence to the PEP 8 style guide.
  # McCabe Complexity Checker: Measures the complexity of your code.
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=200  # Adjust as per your style guide
          - --ignore=F821,F403,F405,F401,W503,E203,E402,E401,W605,E712,E711,F841,E501
          # W503: Line break before binary operator
          # E203: Whitespace before colon
          # E402: Module level import not at top of file
          # E401: Multiple imports on one line
          # W605: Invalid escape sequence
          # E712: Comparison to True/False
          # E711: Comparison to None
          # F841: Unused variable
          # E501: Line too long

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
