
# >>> cy-dir-helper initialize >>>
CY_DIR=/home/mio/Code/buckyball/thirdparty/chipyard
# <<< cy-dir-helper initialize <<<


# >>> build-setup-conda initialize >>>
# line auto-generated by ./build-setup.sh
if ! type conda >& /dev/null; then
    echo "::ERROR:: you must have conda in your environment first"
    return 1  # don't want to exit here because this file is sourced
fi

source $(conda info --base)/etc/profile.d/conda.sh
conda activate buckyball
source /home/mio/Code/buckyball/thirdparty/chipyard/scripts/fix-open-files.sh
# <<< build-setup-conda initialize <<<


# >>> init-submodules initialize >>>
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR=/home/mio/Code/buckyball/thirdparty/chipyard
PATH=$__DIR/software/firemarshal:$PATH
# <<< init-submodules initialize <<<


# >>> bb-dir-helper initialize >>>
BB_DIR=/home/mio/Code/buckyball
# <<< bb-dir-helper initialize <<<

