.git

.codex
.cursor
.direnv
.kiro
.metals
.motia
.vscode
.bsp
.clangd

**/.cache
**/.venv
**/__pycache__
**/node_modules

result
result-*
out
log
tmp
temp

**/build
**/target
**/out
**/log
**/logs

*.log
*.jou
*.vcd
*.fst
*.dump
*.dot
*.tmp
*.swp

vivado*.jou
vivado*.log
webtalk*.jou
webtalk*.log
iter_*.txt
vdbg.*

scripts/docker/.last-image-tag
