[workloads]
tests = [
  "goban-goban-ctest-rvv_kernel-baremetal",
  "goban-goban-ctest-rvv_silu-baremetal",
  "goban-goban-ctest-rvv_swiglu-baremetal",
  "goban-goban-ctest-rvv_snake-baremetal",
  "goban-goban-ctest-rvv_mxfp8_quant-baremetal",
  "goban-goban-ctest-rvv_matmul-baremetal",
  "goban-goban-ctest-mvin_mvout_test-baremetal",
  "goban-goban-ctest-mvin_mvout_stride_test-baremetal",
]
