+incdir+@UVM@/src/ball
+incdir+src
+incdir+src/pkg
+incdir+src/tests
+incdir+@RTL@

@UVM@/src/ball/bb_blink_if.sv
@RTL@/PE.sv
@RTL@/AlwaysOutTransposer.sv
@RTL@/MacUnit.sv
@RTL@/PE_256.sv
@RTL@/Tile.sv
@RTL@/Mesh.sv
@RTL@/TagQueue.sv
@RTL@/ram_6x16.sv
@RTL@/Queue6_TagWithIdAndTotalRows.sv
@RTL@/MeshWithDelays.sv
@RTL@/ram_data_16x128.sv
@RTL@/Queue16_SramReadResp.sv
@RTL@/GemminiExCtrl.sv
@RTL@/LoopMatmulUnroller.sv
@RTL@/LoopConvAddrGen.sv
@RTL@/LoopConvUnroller.sv
@RTL@/LoopCmdEncoder.sv
@RTL@/Arbiter2_LoopCmd.sv
@RTL@/GemminiBall.sv

src/pkg/gemmini_pkg.sv
src/tb_top.sv
