[workloads]
search_path = "workloads/src"
tests = [
  "pebble_mvin_mvout_test-singlecore-baremetal",
  "pebble_mvin_mvout_stride_test-singlecore-baremetal",
  "pebble_transpose_i8_16x16_test-singlecore-baremetal",
  "pebble_transpose_i8_16x32_test-singlecore-baremetal",
  "pebble_transpose_i32_8x16_test-singlecore-baremetal",
  "pebble_transpose_bank_i8_n1_1024x16_test-singlecore-baremetal",
  "pebble_transpose_bank_i8_n2_1024x32_test-singlecore-baremetal",
  "pebble_transpose_bank_i32_n4_1024x16_test-singlecore-baremetal",
  "pebble_matrix_test-singlecore-baremetal",
  "pebble_matrix_matmul_16x16_ones-singlecore-baremetal",
  "pebble_im2col_k1_test-singlecore-baremetal",
  "pebble_im2col_k3_test-singlecore-baremetal",
  "pebble_im2col_k3_partial_test-singlecore-baremetal",
  "pebble_im2col_k3_pad_test-singlecore-baremetal",
  "pebble_im2col_k5_test-singlecore-baremetal",
  "pebble_im2col_k7_test-singlecore-baremetal",
  "pebble_im2col_bank_k1_test-singlecore-baremetal",
  "pebble_im2col_bank_k3_test-singlecore-baremetal",
  "pebble_im2col_bank_k5_test-singlecore-baremetal",
  "pebble_im2col_bank_k7_test-singlecore-baremetal",
  "pebble_conv_im2col_test-singlecore-baremetal",
  "pebble_conv_transpose_test-singlecore-baremetal",
  "pebble_conv_matmul_test-singlecore-baremetal",
  "pebble_quant_fp32_to_int8_test-singlecore-baremetal",
  "pebble_quant_im2col_test-singlecore-baremetal",
  "pebble_quant_transpose_test-singlecore-baremetal",
  "pebble_quant_gemm_test-singlecore-baremetal",
  "pebble_quant_int8_to_fp32_test-singlecore-baremetal",
  "pebble_fp2int_fp32_to_int32_test-singlecore-baremetal",
  "pebble_fp2int_fp32_to_int8_test-singlecore-baremetal",
  "pebble_int2fp_int32_to_fp32_test-singlecore-baremetal",
  "pebble_int2fp_int8_to_fp32_test-singlecore-baremetal",
  "pebble_int2fp_int32_to_int8_test-singlecore-baremetal",
  "pebble_int2fp_int32_to_fp32_col2_test-singlecore-baremetal",
  "pebble_int2fp_int32_to_fp32_col4_test-singlecore-baremetal",
  "pebble_fp2int_bank_fp32_to_int32_test-singlecore-baremetal",
  "pebble_fp2int_bank_fp32_to_int8_test-singlecore-baremetal",
  "pebble_int2fp_bank_int32_to_fp32_test-singlecore-baremetal",
  "pebble_int2fp_bank_int8_to_fp32_test-singlecore-baremetal",
  "pebble_int2fp_bank_int32_to_int8_test-singlecore-baremetal",
  "pebble_int2fp_bank_int32_to_fp32_col2_test-singlecore-baremetal",
  "pebble_int2fp_bank_int32_to_fp32_col4_test-singlecore-baremetal",
]
