[workloads]
search_path = "workloads/src"
tests = [
  "pebble-pebble-ctest-mvin_mvout_test-baremetal",
  "pebble-pebble-ctest-mvin_mvout_stride_test-baremetal",
  "pebble-pebble-mlirtest-base_mvin_mvout_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-base_bank_mvin_mvout_16x16_i8-baremetal",
  "pebble-pebble-ctest-transpose_i8_16x16_test-baremetal",
  "pebble-pebble-ctest-transpose_i8_16x32_test-baremetal",
  "pebble-pebble-ctest-transpose_i32_8x16_test-baremetal",
  "pebble-pebble-ctest-transpose_bank_i8_n1_1024x16_test-baremetal",
  "pebble-pebble-ctest-transpose_bank_i8_n2_1024x32_test-baremetal",
  "pebble-pebble-ctest-transpose_bank_i32_n4_1024x16_test-baremetal",
  "pebble-pebble-mlirtest-bank_transpose_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-ball_transpose_16x16_i8-baremetal",
  "pebble-pebble-ctest-smatmul_16x16_test-baremetal",
  "pebble-pebble-ctest-smatmul_32x16x32_test-baremetal",
  "pebble-pebble-ctest-smatmul_ws_16x16_test-baremetal",
  "pebble-pebble-ctest-smatmul_ws_16x512_test-baremetal",
  "pebble-pebble-mlirtest-bank_smatmul_ws_16x512_i8-baremetal",
  "pebble-pebble-mlirtest-ball_smatmul_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-ball_smatmul_matmul_16x16_i8-baremetal",
  "pebble-pebble-ctest-relu_test-baremetal",
  "pebble-pebble-ctest-relu_bank_256x16_test-baremetal",
  "pebble-pebble-mlirtest-bank_relu_bank_256x16_i32-baremetal",
  "pebble-pebble-mlirtest-linalg_relu_513x17_i32-baremetal",
  "pebble-pebble-ctest-matadd_test-baremetal",
  "pebble-pebble-ctest-matadd_bank_1024x8_i32_test-baremetal",
  "pebble-pebble-mlirtest-bank_matadd_bank_1024x8_i32-baremetal",
  "pebble-pebble-mlirtest-linalg_matmul_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-linalg_transpose_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-linalg_conv_2d_nhwc_hwcf_6x6_k3-baremetal",
  "pebble-pebble-mlirtest-tile_matmul_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-tile_matmul_16x16_f32-baremetal",
  "pebble-pebble-mlirtest-tile_matmul_1x256x120_f32-baremetal",
  "pebble-pebble-mlirtest-tile_matmul_1x576x1024_f32-baremetal",
  "pebble-pebble-mlirtest-tile_matmul_1x1024x1000_f32-baremetal",
  "pebble-pebble-mlirtest-tile_matmul_5x3072x768_f32-baremetal",
  "pebble-pebble-mlirtest-tile_transpose_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-tile_transpose_80x80_f32-baremetal",
  "pebble-pebble-mlirtest-tile_transpose_120x256_f32-baremetal",

  "pebble-pebble-mlirtest-tile_transpose_128x128_dynstride_f32-baremetal",
  "pebble-pebble-mlirtest-tile_transpose_1024x576_dynstride_f32-baremetal",
  "pebble-pebble-mlirtest-tile_transpose_matmul_120x256_f32-baremetal",
  "pebble-pebble-mlirtest-tile_conv2d_6x6_k3-baremetal",
  "pebble-pebble-mlirtest-tile_conv2d_1x1_c16_oc8-baremetal",
  "pebble-pebble-mlirtest-tile_conv2d_1x1_c16_oc24-baremetal",
  "pebble-pebble-mlirtest-tile_conv2d_1x1_c240_oc64-baremetal",
  "pebble-pebble-mlirtest-tile_conv2d_8x8_1x1_c16_oc24-baremetal",
  "pebble-pebble-mlirtest-tile_conv2d_8x8_k3_c2_oc2-baremetal",
  "pebble-pebble-mlirtest-tile_conv2d_12x12_k5-baremetal",
  "pebble-pebble-mlirtest-tile_conv2d_28x28_k5-baremetal",
  "pebble-pebble-mlirtest-bank_im2col_6x6_k3-baremetal",
  "pebble-pebble-mlirtest-ball_im2col_6x6_k3-baremetal",
  "pebble-pebble-mlirtest-bank_fp2int_4x4-baremetal",
  "pebble-pebble-mlirtest-ball_fp2int_4x4-baremetal",
  "pebble-pebble-mlirtest-bank_int2fp_4x4-baremetal",
  "pebble-pebble-mlirtest-ball_int2fp_4x4-baremetal",
  "pebble-pebble-mlirtest-bank_int2fp_channel_4x4-baremetal",
  "pebble-pebble-mlirtest-ball_int2fp_channel_4x4-baremetal",
  "pebble-pebble-ctest-fp2int_i8_signed_test-baremetal",
  "pebble-pebble-ctest-fp2int_i8_rounding_test-baremetal",
  "pebble-pebble-ctest-fp2int_i8_zero_test-baremetal",
  "pebble-pebble-ctest-fp2int_i8_rows_test-baremetal",
  "pebble-pebble-ctest-fp2int_i8_scale_rows_test-baremetal",
  "pebble-pebble-ctest-int2fp_tensor_values_test-baremetal",
  "pebble-pebble-ctest-int2fp_tensor_groups_test-baremetal",
  "pebble-pebble-ctest-int2fp_tensor_rows_test-baremetal",
  "pebble-pebble-ctest-int2fp_channel_lanes_test-baremetal",
  "pebble-pebble-ctest-int2fp_channel_base_test-baremetal",
  "pebble-pebble-ctest-int2fp_channel_two_rows_test-baremetal",
  "pebble-pebble-ctest-im2col_k1_test-baremetal",
  "pebble-pebble-ctest-im2col_k3_test-baremetal",
  "pebble-pebble-ctest-im2col_k3_partial_test-baremetal",
  "pebble-pebble-ctest-im2col_k3_pad_test-baremetal",
  "pebble-pebble-ctest-im2col_k5_test-baremetal",
  "pebble-pebble-ctest-im2col_k7_test-baremetal",
  "pebble-pebble-ctest-im2col_bank_k1_test-baremetal",
  "pebble-pebble-ctest-im2col_bank_k3_test-baremetal",
  "pebble-pebble-ctest-im2col_bank_k5_test-baremetal",
  "pebble-pebble-ctest-im2col_bank_k7_test-baremetal",
  "pebble-pebble-ctest-conv_im2col_test-baremetal",
  "pebble-pebble-ctest-conv_transpose_test-baremetal",
  "pebble-pebble-ctest-conv_im2col_bank_test-baremetal",
  "pebble-pebble-ctest-conv_transpose_bank_test-baremetal",
]
