[workloads]
search_path = "workloads/src"
tests = [
  "mvin_mvout_test-linux",
  "mvin_mvout_stride_test-linux",
  "transpose_test-linux",
  "transpose_16xn_test-linux",
  "matrix_test-linux",
  "matrix_matmul_16x16_ones-linux",
  "im2col_test-linux",
  "conv_im2col_transpose_matmul_test-linux",
  "conv1layer_quant_im2col_transpose_gemm_test-linux",
  "fp2int_fp32_to_int8_test-linux",
]
