[package]
name = "bemu-audio-chip"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bebop-audio"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
snafu = "0.8"
toml = "0.8"
core_bemu = { package = "bemu-audio-encoder", path = "../../../cores/audio-encoder/emu" }
