/* This file is auto-generated. Do not edit. */
#ifndef BB_BALL_ISA_H
#define BB_BALL_ISA_H

#define BB_FUNC7_RELU 50
#define BB_FUNC7_GEMMINI_CONFIG 2
#define BB_FUNC7_GEMMINI_FLUSH 3
#define BB_FUNC7_GEMMINI_PRELOAD 53
#define BB_FUNC7_GEMMINI_COMPUTE_PRELOADED 66
#define BB_FUNC7_GEMMINI_COMPUTE_ACCUMULATED 67
#define BB_FUNC7_GEMMINI_LOOP_WS_CONFIG_BOUNDS 80
#define BB_FUNC7_GEMMINI_LOOP_WS_CONFIG_ADDR_A 81
#define BB_FUNC7_GEMMINI_LOOP_WS_CONFIG_ADDR_B 82
#define BB_FUNC7_GEMMINI_LOOP_WS_CONFIG_ADDR_D 83
#define BB_FUNC7_GEMMINI_LOOP_WS_CONFIG_ADDR_C 84
#define BB_FUNC7_GEMMINI_LOOP_WS_CONFIG_STRIDES_AB 85
#define BB_FUNC7_GEMMINI_LOOP_WS_CONFIG_STRIDES_DC 86
#define BB_FUNC7_GEMMINI_LOOP_WS 87
#define BB_FUNC7_GEMMINI_LOOP_CONV_WS_CONFIG_1 96
#define BB_FUNC7_GEMMINI_LOOP_CONV_WS_CONFIG_2 97
#define BB_FUNC7_GEMMINI_LOOP_CONV_WS_CONFIG_3 98
#define BB_FUNC7_GEMMINI_LOOP_CONV_WS_CONFIG_4 99
#define BB_FUNC7_GEMMINI_LOOP_CONV_WS_CONFIG_5 100
#define BB_FUNC7_GEMMINI_LOOP_CONV_WS_CONFIG_6 101
#define BB_FUNC7_GEMMINI_LOOP_CONV_WS_CONFIG_7 102
#define BB_FUNC7_GEMMINI_LOOP_CONV_WS_CONFIG_8 103
#define BB_FUNC7_GEMMINI_LOOP_CONV_WS_CONFIG_9 104
#define BB_FUNC7_GEMMINI_LOOP_CONV_WS 105
#define BB_FUNC7_BDB_COUNTER 4
#define BB_FUNC7_MXFP2INT 55

#endif
