+incdir+@VERIFY@/uvm/src/ip
+incdir+@VERIFY@/uvm/src/protocol/axis
+incdir+@RESOURCES@
@VERIFY@/uvm/src/ip/package.sv
@VERIFY@/uvm/src/protocol/axis/interface.sv
@VERIFY@/uvm/src/protocol/axis/package.sv
@RESOURCES@/package.sv
@RTL@/Master.sv
@RESOURCES@/master_tb.sv
