# Poly Tile: two Attention Cores and three FFN Cores.

coreDataBytes = 64
xLen = 64
vaddrBits = 39
paddrBits = 56
pgIdxBits = 12
pgLevels = 3
nPMPs = 8

memBallChannelNum = 6

[privateDCache]
enable = false
ways = 4
capacityKB = 256
writeBytes = 8
portFactor = 2
memCycles = 10

[sharedMem]
enable = true
entries = 16384
inputChannels = 5
defaultGroupCount = 1
memCycles = 10

[[cores]]
core_id = 0
name = "attention"
include = "../../../../../cores/attention/configs/default.toml"

[[cores]]
core_id = 1
name = "attention"
include = "../../../../../cores/attention/configs/default.toml"

[[cores]]
core_id = 2
name = "ffn"
include = "../../../../../cores/ffn/configs/default.toml"

[[cores]]
core_id = 3
name = "ffn"
include = "../../../../../cores/ffn/configs/default.toml"

[[cores]]
core_id = 4
name = "ffn"
include = "../../../../../cores/ffn/configs/default.toml"
