[package]
name = "bemu-goban-chip"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bebop-goban"
path = "src/main.rs"

[[test]]
name = "test_verilator"
path = "../../../../bebop/tests/test_verilator.rs"
harness = false
required-features = ["verilator"]

[dependencies]
clap = { version = "4", features = ["derive"] }
snafu = "0.8"
toml = "0.8"
core_bemu = { package = "bemu-goban", path = "../../../cores/goban/emu" }
