[package]
name = "bebop-chip-goban"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bebop-chip-goban"
path = "src/main.rs"

[dependencies]
bebop-bemu = { path = "../configs/generated/bemu" }
clap = { version = "4", features = ["derive"] }

[features]
default = ["bemu"]
bemu = []
p2e = []
verilator = []

[[test]]
name = "test_bemu"
path = "../../../../bebop/tests/test_bemu.rs"
harness = false

[dev-dependencies]
assert_cmd = "2"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
libtest-mimic = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
walkdir = "2"
