[chip]
name = "goban"
topology = "configs/goban.toml"
compilerCore = "goban"

[runtime]
bemu = "emu/Cargo.toml"
bemuCore = "../../cores/goban/emu/Cargo.toml"
bemuTile = "configs/tiles/default.toml"
workloads = "workloads"
