[workloads]
search_path = "workloads/src"
tests = [
  "mvin_mvout_test-linux",
  "mvin_mvout_stride_test-linux",
  "transpose_test-linux",
  "transpose_16xn_test-linux",
  "matrix_test-linux",
  "matrix_matmul_16x16_ones-linux",
]
