[workloads]
search_path = "workloads/src"
tests = [
  "pebble-pebble-ctest-mvin_mvout_test-baremetal",
  "pebble-pebble-ctest-mvin_mvout_stride_test-baremetal",
  "pebble-pebble-mlirtest-base_mvin_mvout_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-base_bank_mvin_mvout_16x16_i8-baremetal",
  "pebble-pebble-ctest-transpose_i8_16x16_test-baremetal",
  "pebble-pebble-ctest-transpose_i8_16x32_test-baremetal",
  "pebble-pebble-ctest-transpose_i32_8x16_test-baremetal",
  "pebble-pebble-mlirtest-bank_transpose_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-ball_transpose_16x16_i8-baremetal",
  "pebble-pebble-ctest-smatmul_16x16_test-baremetal",
  "pebble-pebble-ctest-smatmul_32x16x32_test-baremetal",
  "pebble-pebble-ctest-relu_test-baremetal",
  "pebble-pebble-ctest-matadd_test-baremetal",
  "pebble-pebble-mlirtest-linalg_matmul_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-linalg_transpose_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-linalg_conv_2d_nhwc_hwcf_6x6_k3-baremetal",
  "pebble-pebble-mlirtest-tile_matmul_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-tile_matmul_16x16_f32-baremetal",
  "pebble-pebble-mlirtest-tile_transpose_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-tile_conv2d_6x6_k3-baremetal",
  "pebble-pebble-mlirtest-tile_conv2d_1x1_c16_oc8-baremetal",
  "pebble-pebble-mlirtest-tile_conv2d_1x1_c16_oc24-baremetal",
  "pebble-pebble-mlirtest-tile_conv2d_8x8_k3_c2_oc2-baremetal",
  "pebble-pebble-mlirtest-tile_conv2d_12x12_k5-baremetal",
  "pebble-pebble-mlirtest-bank_im2col_6x6_k3-baremetal",
  "pebble-pebble-mlirtest-ball_im2col_6x6_k3-baremetal",
  "pebble-pebble-ctest-im2col_k1_test-baremetal",
  "pebble-pebble-ctest-im2col_k3_test-baremetal",
  "pebble-pebble-ctest-im2col_k3_partial_test-baremetal",
  "pebble-pebble-ctest-im2col_k3_pad_test-baremetal",
  "pebble-pebble-ctest-im2col_k3_asym_pad_test-baremetal",
  "pebble-pebble-ctest-im2col_k5_test-baremetal",
  "pebble-pebble-ctest-im2col_k7_test-baremetal",
  "pebble-pebble-ctest-conv_im2col_test-baremetal",
  "pebble-pebble-ctest-conv_transpose_test-baremetal",
  "pebble_fp2int_i8_signed_test-singlecore-baremetal",
  "pebble_fp2int_i8_rounding_test-singlecore-baremetal",
  "pebble_fp2int_i8_zero_test-singlecore-baremetal",
  "pebble_fp2int_i8_rows_test-singlecore-baremetal",
  "pebble_fp2int_i8_scale_rows_test-singlecore-baremetal",
  "pebble_int2fp_tensor_values_test-singlecore-baremetal",
  "pebble_int2fp_tensor_groups_test-singlecore-baremetal",
  "pebble_int2fp_tensor_rows_test-singlecore-baremetal",
  "pebble_int2fp_channel_lanes_test-singlecore-baremetal",
  "pebble_int2fp_channel_base_test-singlecore-baremetal",
  "pebble_int2fp_channel_two_rows_test-singlecore-baremetal",
  "pebble_quant_online_gemm_test-baremetal",
  "pebble-pebble-mlirtest-ball_fp2int_4x4-baremetal",
  "pebble-pebble-mlirtest-ball_int2fp_4x4-baremetal",
  "pebble-pebble-mlirtest-ball_int2fp_channel_4x4-baremetal",
]
