#include "monitor/trace.h"
#include "monitor/trace_cfg.h"
#include "utils/debug.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>

// Global log file pointer (shared with monitor.cc)
extern const char *log_path;
static FILE *ctrace_fp = NULL;

// Backdoor write state
static uint32_t bd_write_row_cursor = 0;
static uint64_t bd_write_data_lo = 0;
static uint64_t bd_write_data_hi = 0;

// Backdoor read state
static uint32_t bd_read_row_cursor = 0;

// Backdoor test data generator
// Generates a simple incremental pattern for each row.
// 128-bit = 16 bytes, each byte = (row * 16 + byte_offset) & 0xFF
static void generate_test_data(uint32_t row, uint64_t *data_lo,
                               uint64_t *data_hi) {
  uint8_t data[16];
  for (int i = 0; i < 16; i++) {
    data[i] = (uint8_t)((row * 16 + i) & 0xFF);
  }
  *data_lo = 0;
  *data_hi = 0;
  for (int i = 0; i < 8; i++) {
    *data_lo |= ((uint64_t)data[i]) << (i * 8);
    *data_hi |= ((uint64_t)data[i + 8]) << (i * 8);
  }
}

static void init_ctrace() {
  if (ctrace_fp == NULL && log_path != NULL) {
    ctrace_fp = fopen(log_path, "a");
    if (ctrace_fp == NULL) {
      panic("Failed to open ctrace log file: %s", log_path);
    }
  }
}

static void u128_hex(char *buf, size_t n, unsigned long long hi,
                     unsigned long long lo) {
  int ret = snprintf(buf, n, "0x%016llX%016llX", hi, lo);
  if (ret < 0 || (size_t)ret >= n) {
    panic("snprintf failed in ctrace u128_hex");
  }
}

// ================================================================
// Cycle counter DPI-C
// ================================================================

extern "C" void dpi_ctrace(unsigned char subcmd, unsigned int ctr_id,
                           unsigned long long tag, unsigned long long elapsed,
                           unsigned long long cycle) {
  if (!bdb_trace_on(BDB_TR_CTRACE)) {
    return;
  }
  init_ctrace();

  if (ctrace_fp) {
    switch (subcmd) {
    case 0: // CTR_START
      fprintf(ctrace_fp,
              "{\"type\":\"ctrace\",\"event\":\"ctr_start\",\"ctr_id\":%u,"
              "\"tag\":\"0x%llX\",\"cycle\":%llu}\n",
              ctr_id, tag, cycle);
      break;
    case 1: // CTR_STOP
      fprintf(ctrace_fp,
              "{\"type\":\"ctrace\",\"event\":\"ctr_stop\",\"ctr_id\":%u,"
              "\"tag\":\"0x%llX\",\"elapsed\":%llu,\"cycle\":%llu}\n",
              ctr_id, tag, elapsed, cycle);
      break;
    case 2: // CTR_READ
      fprintf(ctrace_fp,
              "{\"type\":\"ctrace\",\"event\":\"ctr_read\",\"ctr_id\":%u,"
              "\"current\":%llu,\"cycle\":%llu}\n",
              ctr_id, elapsed, cycle);
      break;
    }
    fflush(ctrace_fp);
  }
}

// ================================================================
// Backdoor DPI-C functions
// RTL calls these each iteration. C++ auto-increments row.
// bank_id comes from RTL (instruction encoding), not from C++.
// ================================================================

// RTL calls this to get the next row to read.
// Returns row in [31:0], upper bits = 0.
extern "C" unsigned long long dpi_backdoor_get_read_addr(void) {
  uint32_t row = bd_read_row_cursor;
  bd_read_row_cursor++;
  return (uint64_t)row;
}

// RTL calls this to get the next row to write.
// Also pre-generates test data for this row.
// Returns row in [31:0], upper bits = 0.
extern "C" unsigned long long dpi_backdoor_get_write_addr(void) {
  uint32_t row = bd_write_row_cursor;
  generate_test_data(row, &bd_write_data_lo, &bd_write_data_hi);
  bd_write_row_cursor++;
  return (uint64_t)row;
}

// RTL calls this to get write data (128-bit as lo/hi).
// Data was pre-generated by the preceding get_write_addr call.
extern "C" void dpi_backdoor_get_write_data(unsigned long long *data_lo,
                                            unsigned long long *data_hi) {
  *data_lo = bd_write_data_lo;
  *data_hi = bd_write_data_hi;
}

// RTL calls this after reading SRAM — logs the data to NDJSON trace file
extern "C" void dpi_backdoor_put_read_data(unsigned int bank_id,
                                           unsigned int row,
                                           unsigned long long data_lo,
                                           unsigned long long data_hi) {
  if (!bdb_trace_on(BDB_TR_BANKTRACE)) {
    return;
  }
  init_ctrace();
  if (ctrace_fp) {
    char data_hex[35];
    u128_hex(data_hex, sizeof(data_hex), data_hi, data_lo);
    fprintf(ctrace_fp,
            "{\"type\":\"banktrace\",\"event\":\"backdoor_read\","
            "\"bank_id\":%u,\"row\":%u,\"data\":\"%s\"}\n",
            bank_id, row, data_hex);
    fflush(ctrace_fp);
  }
}

// RTL calls this after writing SRAM — logs the write to NDJSON trace file
extern "C" void dpi_backdoor_put_write_done(unsigned int bank_id,
                                            unsigned int row,
                                            unsigned long long data_lo,
                                            unsigned long long data_hi) {
  if (!bdb_trace_on(BDB_TR_BANKTRACE)) {
    return;
  }
  init_ctrace();
  if (ctrace_fp) {
    char data_hex[35];
    u128_hex(data_hex, sizeof(data_hex), data_hi, data_lo);
    fprintf(ctrace_fp,
            "{\"type\":\"banktrace\",\"event\":\"backdoor_write\","
            "\"bank_id\":%u,\"row\":%u,\"data\":\"%s\"}\n",
            bank_id, row, data_hex);
    fflush(ctrace_fp);
  }
}
