[workloads]
tests = [
  "poly-main-ctest-f32add_groups-baremetal",
  "poly-main-ctest-tlink_lease-baremetal",
  "poly-main-ctest-chip-controllers-multicore-baremetal",
  "poly-main-ctest-chip-ant_mxmm-multicore-baremetal",
  "poly-main-ctest-chip-ant_shared-multicore-baremetal",
  "poly-main-ctest-chip-ant_bank-multicore-baremetal",
  "poly-main-ctest-chip-ant_parallel-multicore-baremetal",
]
