[workloads]
tests = [
  "poly-main-ctest-tutorial-baremetal",
  "poly-main-soctest-clint_timer_interrupt-baremetal",
  "poly-main-soctest-clint_software_interrupt-baremetal",
  "poly-main-soctest-plic_register_access-baremetal",
  "poly-attention-ctest-chip-mesh_shared_bank_roundtrip-baremetal",
  "poly-attention-ctest-chip-mesh_private_bank_move-multicore-baremetal",
  "poly-attention-ctest-chip-task_dma_single-multicore-baremetal",
  "poly-attention-ctest-chip-task_dma_workers-multicore-baremetal",
  "poly-attention-ctest-chip-task_context-multicore-baremetal",
]
