[workloads]
tests = [
  "poly-main-ctest-chip-controllers-linux",
  "poly-main-ctest-f32add_groups-linux",
  "poly-main-ctest-chip-ant_mxmm-linux",
  "poly-main-ctest-chip-ant_shared-linux",
  "poly-main-ctest-chip-ant_bank-linux",
  "poly-main-ctest-chip-ant_parallel-linux",
  "poly-main-ctest-chip-ant_stream-linux",
]
