#!/bin/bash

set -e

export CARGO_HOME=$CONDA_PREFIX/.cargo
export RUSTUP_HOME=$CONDA_PREFIX/.rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable

replace_content ${BBDIR}/env.sh install-rust "# line auto-generated by $0
export CARGO_HOME=$CONDA_PREFIX/.cargo
export RUSTUP_HOME=$CONDA_PREFIX/.rustup
export PATH='$CONDA_PREFIX/.cargo/bin:\$PATH'"
