#!/usr/bin/env bash
set -e

BBDIR=$(git rev-parse --show-toplevel)
source ${BBDIR}/scripts/utils.sh

INSTALL_DIR="${HOME}/.local/bin"
mkdir -p "${INSTALL_DIR}"

SCALAFMT_VERSION=$(grep "^version" ${BBDIR}/arch/.scalafmt.conf 2>/dev/null | sed 's/version = //;s/"//g' | tr -d ' ' || echo "3.9.6")

if command -v cs &> /dev/null; then
  cs install scalafmt:${SCALAFMT_VERSION} --install-dir "${INSTALL_DIR}"
else
  echo "Downloading coursier..."
  curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz | gzip -d > /tmp/cs
  chmod +x /tmp/cs
  /tmp/cs install scalafmt:${SCALAFMT_VERSION} --install-dir "${INSTALL_DIR}"
  rm /tmp/cs
fi

replace_content ${BBDIR}/env.sh install-scalafmt "# line auto-generated by $0
export PATH=${INSTALL_DIR}:\${PATH}"

echo "✓ Scalafmt ${SCALAFMT_VERSION} installed to ${INSTALL_DIR}"
