[chip]
name = "pebble"
topology = "configs/pebble.toml"
compilerCore = "pebble"

[runtime]
bemu = "../../cores/pebble/emu/Cargo.toml"
kernel = "kernel"
workloads = "workloads"
regression = "regression"
