[designs]
include = "designs/goban.toml"

[sims]
verilator = "sims.verilator.GobanVerilatorTarget"
p2e = "sims.p2e.GobanP2ETarget"

[uvm]
balls = ["smatmul", "toint8", "int2fp", "transpose"]
ips = []
