#!/usr/bin/env python3
"""Offline NLI (non-uniform linear interpolation) table generation for SiLU.

Target: SiLU(x) = x * sigmoid(x) = x / (1 + exp(-x)), over INT8 x in [-128, 127].

Scheme (matches the NliBall RTL + BEMU emulator bit-exactly):
  * 16 non-uniform segments over the signed INT8 domain.
  * 15 interior cutpoints c_1..c_15 (INT8, ascending). c_0 = -128, c_16 = 128.
  * Segment i covers x in [c_i, c_{i+1}) and is the chord through the knots:
        slope_i     = (f(c_{i+1}) - f(c_i)) / (c_{i+1} - c_i)
        intercept_i = f(c_i) - slope_i * c_i
  * slope is quantized to Q7 (round(slope*128), clamp to [-128,127]).
  * intercept is quantized to INT8 (round, clamp).
  * Hardware computes: out = clamp( (slope_q7 * x) >> 7 + intercept_q, -128, 127 )
    where `>>` is arithmetic shift (floor toward -inf).

The interior cutpoints are optimized with coordinate descent to minimise the
maximum absolute error against the true SiLU across the whole INT8 domain.
"""
from __future__ import annotations

import math

LO = -128
HI = 127
N_SEG = 16          # 16 segments -> 15 interior cutpoints
Q7 = 128            # slope fixed-point scale


def silu(x: float) -> float:
    # Numerically stable SiLU.
    if x >= 0.0:
        return x / (1.0 + math.exp(-x))
    e = math.exp(x)
    return x * e / (1.0 + e)


def clamp8(v: float) -> int:
    return max(-128, min(127, round(v)))


def build_table(cutpoints):
    """Return (slopes_q7, intercepts_q) for 16 segments given 15 cutpoints."""
    knots = [LO] + list(cutpoints) + [128]  # c_0 .. c_16 (16 segments)
    slopes = []
    intercepts = []
    for i in range(N_SEG):
        lo, hi = knots[i], knots[i + 1]
        f_lo, f_hi = silu(lo), silu(hi)
        slope = (f_hi - f_lo) / (hi - lo)
        inter = f_lo - slope * lo
        slopes.append(clamp8(slope * Q7))
        intercepts.append(clamp8(inter))
    return slopes, intercepts


def eval_int(x: int, cutpoints, slopes, intercepts) -> int:
    seg = 0
    for c in cutpoints:
        if x >= c:
            seg += 1
    prod = slopes[seg] * x
    term = prod >> 7          # arithmetic shift: floor for negatives
    return max(-128, min(127, term + intercepts[seg]))


def max_error(cutpoints, slopes, intercepts):
    worst = 0.0
    worst_x = 0
    for x in range(LO, HI + 1):
        ref = silu(x)
        approx = eval_int(x, cutpoints, slopes, intercepts)
        err = abs(approx - ref)
        if err > worst:
            worst, worst_x = err, x
    return worst, worst_x


def mean_error(cutpoints, slopes, intercepts):
    total = 0.0
    for x in range(LO, HI + 1):
        ref = silu(x)
        approx = eval_int(x, cutpoints, slopes, intercepts)
        total += abs(approx - ref)
    return total / (HI - LO + 1)


def optimize(cutpoints, slopes, intercepts):
    """Coordinate descent over interior cutpoints, minimising max error."""
    current_max, _ = max_error(cutpoints, slopes, intercepts)
    improved = True
    iters = 0
    while improved and iters < 4000:
        improved = False
        iters += 1
        for i in range(len(cutpoints)):
            lo_bound = LO + 1 if i == 0 else cutpoints[i - 1] + 1
            hi_bound = HI - (len(cutpoints) - 1 - i) if i == len(cutpoints) - 1 else cutpoints[i + 1] - 1
            best = cutpoints[i]
            best_val = current_max
            for cand in range(lo_bound, hi_bound + 1):
                if cand == cutpoints[i]:
                    continue
                trial = list(cutpoints)
                trial[i] = cand
                s2, t2 = build_table(trial)
                m2, _ = max_error(trial, s2, t2)
                if m2 < best_val - 1e-9:
                    best_val, best = m2, cand
            if best != cutpoints[i]:
                cutpoints[i] = best
                slopes, intercepts = build_table(cutpoints)
                current_max = best_val
                improved = True
    return cutpoints, slopes, intercepts


def main():
    # Heuristic initial non-uniform spacing: denser near 0 (max curvature),
    # sparser at the saturating extremes. Asymmetric because SiLU(-x) != SiLU(x).
    init = [-96, -64, -44, -30, -20, -13, -8, -4, -1, 2, 5, 9, 16, 28, 48]
    cutpoints = list(init)
    slopes, intercepts = build_table(cutpoints)
    cutpoints, slopes, intercepts = optimize(cutpoints, slopes, intercepts)

    worst, worst_x = max_error(cutpoints, slopes, intercepts)
    mean = mean_error(cutpoints, slopes, intercepts)

    def c_arr(name, vals):
        body = ", ".join(str(v) for v in vals)
        return f"static const int8_t {name}[{len(vals)}] = {{ {body} }};"

    print("// Auto-generated by examples/balls/nli/scripts/gen_silu_table.py")
    print("// SiLU (Swish) NLI table: 16 non-uniform segments, INT8/Q7 fixed point.")
    print(c_arr("silu_cutpoints", cutpoints))
    print(c_arr("silu_slopes", slopes))
    print(c_arr("silu_intercepts", intercepts))
    print("")
    print(f"// max_abs_error={worst:.4f} @ x={worst_x}")
    print(f"// mean_abs_error={mean:.4f}")
    print(f"// cutpoints={list(cutpoints)}")
    print(f"// slopes={list(slopes)}")
    print(f"// intercepts={list(intercepts)}")


if __name__ == "__main__":
    main()
