load(":chip_json_repo.bzl", "ensure_chip_bundle_pb2", "run_chip_json")

def _safe_name(chip):
    name = chip.replace("-", "_")
    if not name:
        fail("empty chip directory name")
    allowed = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_"
    if name[0] not in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ":
        fail("chip directory name is not a valid Bazel identifier base: %s" % chip)
    i = 0
    for _ in range(len(name)):
        if name[i] not in allowed:
            fail("chip directory name has unsupported characters: %s" % chip)
        i += 1
    return name

def _pkg_exists(root, core, parts):
    pkg = root.get_child("examples").get_child("cores").get_child(core)
    for part in parts:
        pkg = pkg.get_child(part)
    return pkg.get_child("BUILD.bazel").exists or pkg.get_child("BUILD").exists

def _bb_chips_repo_impl(repo_ctx):
    root = repo_ctx.path(Label("//:MODULE.bazel")).dirname
    chips_dir = root.get_child("examples").get_child("chips")
    if not chips_dir.exists:
        fail("examples/chips does not exist")
    repo_ctx.watch(chips_dir)

    settings = []
    isa_entries = []
    bank_entries = []
    ctest_entries = []
    mlir_entries = []
    compiler_entries = []
    emu_main_entries = []
    topology_entries = []
    bemu_tile_index_entries = []
    chips = []

    pb2_dir = ensure_chip_bundle_pb2(repo_ctx, root)

    entries = chips_dir.readdir()
    by_name = {entry.basename: entry for entry in entries}
    for chip in sorted(by_name.keys()):
        entry = by_name[chip]
        if not entry.get_child("chip.toml").exists:
            continue

        idx = run_chip_json(
            repo_ctx,
            root,
            "%s.index.json" % chip,
            ["--chip", chip],
            chip,
            pb2_dir,
        )
        core = idx.get("compilerCore", "")
        topo_rel = idx.get("topology", "")
        chip_main = idx.get("chipMain", "")
        bemu_tile_index = idx.get("bemuTileIndex", 0)
        if type(core) != "string":
            fail("%s: compilerCore must be a string" % chip)
        if type(topo_rel) != "string" or not topo_rel:
            fail("%s: chip index missing topology" % chip)
        if type(chip_main) != "string" or type(bemu_tile_index) != "int":
            fail("%s: chip index missing chipMain/bemuTileIndex" % chip)
        if bemu_tile_index < 0:
            fail("%s: bemuTileIndex must be non-negative" % chip)

        safe = _safe_name(chip)
        chips.append(chip)
        settings.append("""
config_setting(
    name = "chip_%s",
    flag_values = {"@@//bazel/config:chip": "%s"},
)
""" % (safe, chip))

        if core:
            has_isa = _pkg_exists(root, core, ["isa"])
            has_bank = _pkg_exists(root, core, ["configs", "memdomains"])
            if has_isa != has_bank:
                fail(
                    ("%s: topology core %r must provide both isa/ and " +
                     "configs/memdomains/ (or neither)") % (chip, core),
                )
            if has_isa:
                if not _pkg_exists(root, core, ["workloads"]):
                    fail("%s: topology core %r must provide workloads/" % (chip, core))
                isa_entries.append(
                    '        ":chip_%s": "@@//examples/cores/%s/isa:ballISA",' % (safe, core),
                )
                bank_entries.append(
                    '        ":chip_%s": "@@//examples/cores/%s/configs/memdomains:bank_params",' %
                    (safe, core),
                )
                ctest_entries.append(
                    '        ":chip_%s": "@@//examples/cores/%s/workloads:ctests",' % (safe, core),
                )
                mlir_entries.append(
                    '        ":chip_%s": "@@//examples/cores/%s/workloads:mlir_tests",' % (safe, core),
                )

        compiler_entries.append('        "@bb_chips//:chip_%s": "%s",' % (safe, core))
        emu_main_entries.append('        "@bb_chips//:chip_%s": "%s",' % (safe, chip_main))
        bemu_tile_index_entries.append('        "@bb_chips//:chip_%s": %d,' % (safe, bemu_tile_index))
        topology_entries.append('        "@bb_chips//:chip_%s": "%s",' % (safe, topo_rel))

    if not chips:
        fail("no examples/chips/*/chip.toml found")
    if not isa_entries:
        fail("no chip has a unique topology core with isa/ and configs/memdomains/")
    if not ctest_entries:
        fail("no chip has a unique topology core with workloads/")

    lines = [
        "# Generated by chip_json.py — do not edit.",
        'package(default_visibility = ["//visibility:public"])',
        "",
    ]
    lines.extend(settings)
    for name, entries in (
        ("ballISA", isa_entries),
        ("bank_params", bank_entries),
        ("ctests", ctest_entries),
        ("mlir_tests", mlir_entries),
    ):
        lines += ["", "alias(", '    name = "%s",' % name, "    actual = select({"]
        lines.extend(entries)
        lines += ["    }),", ")"]
    lines.append("")

    repo_ctx.file("BUILD.bazel", "\n".join(lines))
    repo_ctx.file("WORKSPACE", "")

    chips_bzl = ["# Generated by chip_json.py — do not edit.", "CHIPS = ["]
    chips_bzl.extend(['    "%s",' % c for c in chips])
    chips_bzl += ["]", ""]
    for var, entries in (
        ("CHIP_TOPOLOGY", topology_entries),
        ("COMPILER_CORE", compiler_entries),
        ("CHIP_EMU_MAIN", emu_main_entries),
        ("CHIP_BEMU_TILE_INDEX", bemu_tile_index_entries),
    ):
        chips_bzl += ["%s = select({" % var]
        chips_bzl.extend(entries)
        chips_bzl += ["})", ""]
    repo_ctx.file("chips.bzl", "\n".join(chips_bzl))

bb_chips_repo = repository_rule(
    implementation = _bb_chips_repo_impl,
    local = True,
)
