"""Generate core workload filegroups from isa/BUILD.bazel balldomain labels."""

load(":chip_json_repo.bzl", "ensure_chip_bundle_pb2", "run_chip_json")

def _field(content, key, path):
    for raw in content.splitlines():
        line = raw.split("#", 1)[0].strip()
        if line.endswith(","):
            line = line[:-1].rstrip()
        if not line.startswith(key):
            continue
        rest = line[len(key):].strip()
        if not rest.startswith("="):
            continue
        rest = rest[1:].strip()
        if len(rest) < 2 or rest[0] != '"' or rest[-1] != '"':
            fail("%s: %s must be a quoted string" % (path, key))
        value = rest[1:-1]
        if not value:
            fail("%s: %s is empty" % (path, key))
        return value
    return None

def _ws_rel(root, path):
    root_s = str(root)
    path_s = str(path)
    prefix = root_s + "/"
    if not path_s.startswith(prefix):
        fail("path escapes workspace: %s" % path_s)
    return path_s[len(prefix):]

def _label_to_path(root, label, src):
    if not label.startswith("//"):
        fail("%s: balldomain label must be absolute (//pkg:file): %s" % (src, label))
    rest = label[2:]
    if ":" not in rest:
        fail("%s: balldomain label must be //pkg:file: %s" % (src, label))
    pkg, name = rest.split(":", 1)
    if not pkg or not name:
        fail("%s: invalid balldomain label: %s" % (src, label))
    path = root
    for part in pkg.split("/"):
        path = path.get_child(part)
    path = path.get_child(name)
    if not path.exists:
        fail("%s: balldomain file does not exist: %s" % (src, label))
    return path

def _bb_cores_repo_impl(repo_ctx):
    root = repo_ctx.path(Label("//:MODULE.bazel")).dirname
    cores_dir = root.get_child("examples").get_child("cores")
    if not cores_dir.exists:
        fail("examples/cores does not exist")
    repo_ctx.watch(cores_dir)

    data_lines = [
        "# Generated by chip_json.py — do not edit.",
        "CORE_WORKLOADS = {",
    ]

    pb2_dir = ensure_chip_bundle_pb2(repo_ctx, root)

    entries = cores_dir.readdir()
    by_name = {entry.basename: entry for entry in entries}
    for core in sorted(by_name.keys()):
        entry = by_name[core]
        isa_build = entry.get_child("isa").get_child("BUILD.bazel")
        if not isa_build.exists:
            isa_build = entry.get_child("isa").get_child("BUILD")
        if not isa_build.exists:
            continue
        repo_ctx.watch(isa_build)
        isa_text = repo_ctx.read(isa_build)
        balldomain_label = _field(isa_text, "balldomain", str(isa_build))
        if not balldomain_label:
            fail("%s: missing balldomain = \"//...\" for ball_isa" % isa_build)

        balldomain_rel = _ws_rel(root, _label_to_path(root, balldomain_label, str(isa_build)))
        data = run_chip_json(
            repo_ctx,
            root,
            "%s.balls.json" % core,
            ["--balldomain", balldomain_rel],
            balldomain_rel,
            pb2_dir,
        )
        ball_dirs = data.get("ballDirs")
        if type(ball_dirs) != "list":
            fail("%s: ballDirs missing" % balldomain_rel)

        ctests = []
        mlir = []
        for directory in ball_dirs:
            ball_root = root.get_child("examples").get_child("balls").get_child(directory)
            ball_build = ball_root.get_child("BUILD.bazel")
            if not ball_build.exists:
                ball_build = ball_root.get_child("BUILD")
            if not ball_build.exists:
                fail("%s: ball %s missing examples/balls/%s/BUILD.bazel" % (
                    balldomain_rel,
                    directory,
                    directory,
                ))
            repo_ctx.watch(ball_build)
            if not ball_root.get_child("workloads").get_child("ctests").exists:
                fail("%s: ball %s missing workloads/ctests/" % (balldomain_rel, directory))
            ctests.append("//examples/balls/%s:ctests" % directory)
            if ball_root.get_child("workloads").get_child("mlir_tests").exists:
                mlir.append("//examples/balls/%s:mlir_tests" % directory)

        data_lines.append('    "%s": {' % core)
        data_lines.append('        "ctests": [')
        for tgt in ctests:
            data_lines.append('            "%s",' % tgt)
        data_lines.append("        ],")
        data_lines.append('        "mlir_tests": [')
        for tgt in mlir:
            data_lines.append('            "%s",' % tgt)
        data_lines.append("        ],")
        data_lines.append("    },")

    if len(data_lines) == 2:
        fail("no examples/cores/*/isa/BUILD.bazel with balldomain found")

    data_lines.append("}")
    data_lines.append("")
    data_lines.append("def core_workloads(core):")
    data_lines.append('    """Emit ctests/mlir_tests filegroups for one core package."""')
    data_lines.append("    if core not in CORE_WORKLOADS:")
    data_lines.append(
        '        fail("unknown core %r; known: %s" % (core, sorted(CORE_WORKLOADS.keys())))',
    )
    data_lines.append("    entry = CORE_WORKLOADS[core]")
    data_lines.append("    native.filegroup(")
    data_lines.append('        name = "ctests",')
    data_lines.append('        srcs = entry["ctests"],')
    data_lines.append("    )")
    data_lines.append("    native.filegroup(")
    data_lines.append('        name = "mlir_tests",')
    data_lines.append('        srcs = entry["mlir_tests"],')
    data_lines.append("    )")
    data_lines.append("")

    repo_ctx.file("workloads.bzl", "\n".join(data_lines))
    repo_ctx.file("BUILD.bazel", 'package(default_visibility = ["//visibility:public"])\n')
    repo_ctx.file("WORKSPACE", "")

bb_cores_repo = repository_rule(
    implementation = _bb_cores_repo_impl,
    local = True,
)
