# name: CI-test
# run-name: ${{ github.actor }} is running CI-test 🚀
# on:
#   push:
#     branches:
#       - dev

# jobs:
#   CI-Pull:
#     name: CI Pull
#     runs-on: cpu-server
#     steps:
#       - name: Pull from the repository 
#         run: |
#           source ~/.zshrc
#           setproxy
#           git reset --hard origin/${{ github.ref }}
#           git pull origin ${{ github.ref }}
#       - run: echo "🍏 pull from repository ${{ job.status }}."

#   Build Workload:
#     name: Build Workload
#     runs-on: cpu-server
#     needs: CI-Pull
#     steps:
#       - name: Deploy
#         shell: zsh {0}
#         run: |
#           source ~/.zshrc
#           buckyball_exec
#           bbdev workload --build --port 5600
#       - run: echo "🍏 Build Workload ${{ job.status }}."

#   Build Verilator:
#     name: Build Verilator
#     runs-on: cpu-server
#     needs: CI-Pull
#     steps:
#       - name: Deploy
#         shell: zsh {0}
#         run: |
#           source ~/.zshrc
#           buckyball_exec
#           bbdev verilator --verilog
#       - run: echo "🍏 Build Verilator ${{ job.status }}."

#   Run Smoke Test:
#     name: Run Smoke Test
#     runs-on: cpu-server
#     needs: CI-Pull
#     steps:
#       - name: Deploy
#         shell: zsh {0}
#         run: |
#           source ~/.zshrc
#           buckyball_exec