name: Document Deployment
run-name: ${{ github.actor }} is running Document Deployment 🚀
on:
  push:
    branches:
      - dev

jobs:
  Doc-Pull:
    name: Doc Pull
    runs-on: cpu-server
    steps:
      - name: Pull from the repository 
        run: |
          source ~/.zshrc
          setproxy
          git reset --hard origin/${{ github.ref }}
          git pull origin ${{ github.ref }}
      - run: echo "🍏 pull from repository ${{ job.status }}."

  Doc-Build:
    name: Doc Build
    runs-on: cpu-server
    needs: Doc-Pull
    steps:
      - name: Deploy
        shell: zsh {0}
        run: |
          source ~/.zshrc
          buckyball_exec
          cd ${BBDIR}/docs/bb-note
          mdbook serve --open -p 3001
      - run: echo "🍏 Document is running on port 3001 ${{ job.status }}."

