name: Buckyball CI (PR)
run-name: ${{ github.actor }} is running PR Test 🚀
on:
  pull_request:
    branches:
      - '*'

jobs:
  PR-Test:
    name: PR Test
    runs-on: cpu-server
    steps:
      - name: Print information
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🔎 PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          echo "🔎 Branch: ${{ github.head_ref }} -> ${{ github.base_ref }}"
          echo "🔎 Repository: ${{ github.repository }}"

      - name: Pull from the repository
        shell: zsh {0}
        run: |
          source ~/.zshrc
          buckyball_exec
          setproxy
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/head:refs/remotes/origin/pr/${{ github.event.pull_request.number }}
          git clean -fd
          git reset --hard ${{ github.sha }}

      - name: Build Workloads
        shell: zsh {0}
        run: |
          source ~/.zshrc
          buckyball_exec
          setproxy
          bbdev workload --build

      - name: Build Verilator
        shell: zsh {0}
        run: |
          source ~/.zshrc
          buckyball_exec
          bbdev verilator --clean
          bbdev verilator --verilog
          bbdev verilator --build '--jobs 16'

      - name: Smoke Test
        shell: zsh {0}
        run: |
          source ~/.zshrc
          buckyball_exec
          bbdev sardine --run '--workload ctest'

      - run: echo "🍏 PR Test is ${{ job.status }}."
