name: pre-commit
run-name: ${{ github.actor }} is running pre-commit 🚀

on:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  pre-commit:
    name: pre-commit
    runs-on: check
    env:
      ALL_PROXY: socks5h://127.0.0.1:7890
    steps:
      - name: Reset to clean state
        shell: zsh {0}
        run: |
          cd ~/Code/buckyball
          git fetch --force --prune origin "${{ github.ref }}"
          git checkout --detach FETCH_HEAD
          git reset --hard FETCH_HEAD
          git clean -ffd
          git submodule sync
          git submodule update --init --force
          for submodule in bbdev bebop compiler/thirdparty/buddy-mlir; do
            git -C "$submodule" reset --hard
            git -C "$submodule" clean -ffd
          done

      - name: Check pre-commit
        shell: zsh {0}
        run: |
          cd ~/Code/buckyball
          nix develop -c pre-commit run --all-files --show-diff-on-failure --color=always
